### ISSUE TITLE
Cannot find module.. 

### ISSUE THREAD

**Issue by msk-psp** [janeasystems/nodejs-mobile#100]
`08-01 17:47:45.778 14615-14637/com.example.jino.nodejs E/NODEJS-MOBILE: module.js:529
        throw err;
        ^
    
    Error: Cannot find module 'left-pad'
        at Function.Module._resolveFilename (module.js:527:15)
        at Function.Module._load (module.js:476:23)
        at Module.require (module.js:568:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/data/data/com.example.jino.nodejs/files/nodejs-project/main.js:2:15)
        at Module._compile (module.js:624:30)
        at Object.Module._extensions..js (module.js:635:10)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12)
        at Function.Module._load (module.js:500:3)
`

main.js

`var http = require('http');
var leftPad = require('left-pad');
var versions_server = http.createServer( (request, response) => {
  response.end('Versions: ' + JSON.stringify(process.versions) + ' left-pad: ' + leftPad(42, 5, '0'));
});
versions_server.listen(3000);`

package.json
`{
  "name": "native-gradle-node-project",
  "version": "0.0.1",
  "description": "node part of the project",
  "main": "main.js",
  "author": "janeasystems",
  "license": "",
  "dependencies": {
    "left-pad": "1.3.0"
  }
}`

* **Version**: node 8.6.0
* **Platform**: windows 10 64bit
* **Subsystem**:  example on repository

Hi,

Sorry poor question, I'm quite a beginner of nodejs-mobile

I just trying to run examples on repo, 

but it crashed with the error even I put dependencies in package.json

also can't find module when I added iconv-lite in dependencies and require("iconv-lite")
thank you

**Comment by jaimecbernardo** [comment]
Hi @Minsoo-kim92 , did you run [this instruction](https://github.com/janeasystems/nodejs-mobile-samples/tree/86d21650f8fd12e00f99b20e26f92824cc28bce2/android/native-gradle-node-folder#how-to-run):

> Run `npm install` inside `android/native-gradle-node-folder/app/src/main/assets/nodejs-project/`.

If you've run it, you'll find to have the `left-pad` module inside `android/native-gradle-node-folder/app/src/main/assets/nodejs-project/node_modules/left-pad` .

**Comment by msk-psp** [comment]
I didn't know that I have to install modules I'll use, thanks
