### ISSUE TITLE
Android: Error: Duplicate resources (.gz in node_modules)

### ISSUE THREAD

**Issue by futpib** [janeasystems/nodejs-mobile#101]
If you have (for example) `joi-browser` as a dependency of your `nodejs-project`, you get the following error from `react-native run-android`:

```
Could not merge source set folders: 
[nodejs-project/node_modules/joi-browser/dist/joi-browser.min.js]
/home/futpib/code/app/nodejs-assets/nodejs-project/node_modules/joi-browser/dist/joi-browser.min.js
[nodejs-project/node_modules/joi-browser/dist/joi-browser.min.js]
/home/futpib/code/app/nodejs-assets/nodejs-project/node_modules/joi-browser/dist/joi-browser.min.js.gz:
Error: Duplicate resources
```

Workaround: remove the `*.gz` file (if you don't need it).

**Comment by jaimecbernardo** [comment]
Hi @futpib ,
That is indeed, a workaround for the issue.
I've given a test to use `joi-browser` in a project and the error didn't occur to me.
This line should have prevented it: https://github.com/janeasystems/nodejs-mobile-react-native/blob/187551aeabb71eb5964d19b496d219c6598f88fd/android/build.gradle#L68

What version of `nodejs-mobile-react-native` are you using?

**Comment by futpib** [comment]
@jaimecbernardo I'm using `0.1.3`. Thanks. Sorry, I forgot I was not on the latest version.
