### ISSUE TITLE
The cordova plugin doesn't work

### ISSUE THREAD

**Issue by ghost** [janeasystems/nodejs-mobile#105]
Version: 8.10.0
Platform: windows 10 64 bit

Hi, 
I have this error running the cordova-mobile-nodejs plugin in android:
```
D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 1470 : Uncaught Error: Module nodejs-mobile-cordova.nodejs does not exist.
I/chromium: [INFO:CONSOLE(1470)] "Uncaught Error: Module nodejs-mobile-cordova.nodejs does not exist.", source: file:///android_asset/www/cordova.js (1470)
```

I use this platform:
cordova cli: 7.0.0
android platform: 6.3.0
mobile-nodejs-cordova: 0.2.0

**Comment by jaimecbernardo** [comment]
Hi,

I've given it a try on a Windows10 machine, by running the following commands:
```
cordova create hello com.example.hello HelloWorld
cd hello
cordova platform add android@6.3.0
cordova plugin add nodejs-mobile-cordova@0.2.0
.\plugins\nodejs-mobile-cordova\install\sample-project\copy-sample-project.sh
cordova run android
```
I've checked logcat and I've got the correct behavior.

From other reports, it is possibly a configuration issue on the development machine.
Please check this other related issue for further diagnosis: https://github.com/janeasystems/nodejs-mobile/issues/52

**Comment by ghost** [comment]
Hi,
are you sure that you have performed it on Windows machine? I see that the "copy-sample-project.hs" is a bash script for linux...

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,
Yes, I did test it on Windows.
I have the Git Bash tools in my system's path, so I was able to run the shell script.
That script copies a sample project from the plugin structure into your app:
https://github.com/janeasystems/nodejs-mobile-cordova/tree/79092d967a1c6b35abd0f7b2f1dd436582f439ec#set-up-project-files-using-the-helper-script

You also have manual steps right after that section in case you can't run the script.
All the script does is copying some files: https://github.com/janeasystems/nodejs-mobile-cordova/blob/79092d967a1c6b35abd0f7b2f1dd436582f439ec/install/sample-project/copy-sample-project.sh

**Comment by ghost** [comment]
Hi, 
yes I read that the script copies a sample example project. However the error persists.

```
9.161 3201-3201/com.example.hello D/SystemWebChromeClient: file:///android_asset/www/plugins/nodejs-mobile-cordova/www/nodejs_apis.js: Line 21 : Uncaught SyntaxError: Unexpected token ...
08-13 07:59:09.161 3201-3201/com.example.hello I/chromium: [INFO:CONSOLE(21)] "Uncaught SyntaxError: Unexpected token ...", source: file:///android_asset/www/plugins/nodejs-mobile-cordova/www/nodejs_apis.js (21)
08-13 07:59:09.161 3201-3201/com.example.hello D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 1470 : Uncaught Error: Module nodejs-mobile-cordova.nodejs does not exist.

```
It seems that the error is in the sintax in the file nodejs_apis.js:

```
 constructor(_event, ..._payload) {

```

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,
That operator is the rest operator, which is valid javascript syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

It's possible that the device you are testing on doesn't support this syntax on its WebView. Which device are you testing on? Which Android OS version is it using?

**Comment by ghost** [comment]
Hi,
My device is a Nexus 4 API 23 with android 6.0.0 target

**Comment by ghost** [comment]
How I can update the WebView? Maybe with an android platform 7.0.0? But probably it's not compatible with cordova 7.0.0...

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,

The WebView comes as part of the Android OS, so the way to update it would be to update your device.
While not having a 6.0 device available currently, I've tested on a Android 5.1 device with success.

I thought the LG Nexus 4 was only upgrade-able to Android version 5.1 (API Level 22) . Are you running an unsupported ROM on your device?

**Comment by ghost** [comment]
I downgrade my device to Android version 5.1 (API Level 22), but now there is another error about webView:

```
 5341-5341/com.example.hello D/SystemWebChromeClient: file:///android_asset/www/plugins/nodejs-mobile-cordova/www/nodejs_apis.js: Line 6 : Uncaught SyntaxError: Use of const in strict mode.
08-13 11:11:41.267 5341-5341/com.example.hello I/chromium: [INFO:CONSOLE(6)] "Uncaught SyntaxError: Use of const in strict mode.", source: file:///android_asset/www/plugins/nodejs-mobile-cordova/www/nodejs_apis.js (6)
08-13 11:11:41.267 5341-5341/com.example.hello D/SystemWebChromeClient: file:///android_asset/www/plugins/nodejs-mobile-cordova/www/nodejs_events.js: Line 186 : Uncaught SyntaxError: Use of const in strict mode.
08-13 11:11:41.267 5341-5341/com.example.hello I/chromium: [INFO:CONSOLE(186)] "Uncaught SyntaxError: Use of const in strict mode.", source: file:///android_asset/www/plugins/nodejs-mobile-cordova/www/nodejs_events.js (186)

```

**Comment by haleminh** [comment]
I think should have plan to upgrade Android, Google policy for Android SDK 26 had been going on 1st Aug 2018 yet. 

All plan to try to use janeasystems in production now is impossible.

**Comment by ghost** [comment]
Hi @haleminh,
I don't understand your consideration. The problem is about the android webView. So I tried to install also the cordova crosswalk plugin, but then I found an error for the compatibility with the NDK

**Comment by haleminh** [comment]
Hi @amanganiello90,

Sorry, I forgot mention @jaimecbernardo. The cordova plugin I tested working with android 6.4.0 or earlier version. But that android version not satify google play requirements now. It should upgrade to newer android version.

**Comment by ghost** [comment]
ok @haleminh,
can you tell me a cordova version, android platform version and a device compatible with your plugin? I want to run my node.js script in cordova...

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 , LG Nexus 4 seems to have received its latest official update in May 2015, over 3 years ago.

It seems to be missing some JavaScript features. As a possible workaround for this, it may be possible to convert the plugin's Javascript to pre-ES6 Javascript, but it will probably come at a performance cost. I've pushed a branch to the repo to test this. To use it, please run the following for your project:
```
cordova plugin remove nodejs-mobile-cordova
cordova plugin add https://github.com/janeasystems/nodejs-mobile-cordova#staging-babel-UI-runtime
```

This will install the `staging-babel-UI-runtime` branch instead of the official release.

In terms of compatible devices, the plugin has been successfully tested on many Android 7.0 and Android 8.0 devices. The Nexus 6P is an example of such a device.

Please let us know of what results you get.

**Comment by jaimecbernardo** [comment]
Hi @haleminh,

"cordova-android" seems to be targeting API level 26 (`targetSdkVersion`) since version 6.3.0, so I'm not sure what you're talking about.
What issues did you have while submitting to the play store?

**Comment by quanganh206** [comment]
Hi @jaimecbernardo,

It's target version if you set min version to 26. You will see some error because plugin use some api in sdk 21. New requirements in Google Play for android app is min sdk 26.

**Comment by haleminh** [comment]
Hi @jaimecbernardo,

It the same problem with @quanganh206. I think upgrade to meet cordova android 7.1.1 or newer will solve problem.

**Comment by jaimecbernardo** [comment]
Hi @quanganh206 , @haleminh ,

What is the exact error you are getting?

The `cordova-android 7.1.1` release seems to have the minimum sdk version at 19: https://github.com/apache/cordova-android/blob/rel/7.1.1/framework/AndroidManifest.xml#L22

**Comment by ghost** [comment]
Hi @quanganh206,
To use android 7 (Nougat), you have to update cordova version to 8.0.0 that is not supported from the plugin

**Comment by quanganh206** [comment]
@jaimecbernardo: you should set min version to 26 it will inform and api 21 error. All new android app need use sdk 26 api.

@amanganiello90: yes, but you can still use cordova 8.0 to install android cordova 6.4.0 to test without any problems.

**Comment by quanganh206** [comment]
@jaimecbernardo: sorry, one more question not relate to that topic. Do you have plan to make plugin with Flutter? If you have I think I can join and working with you.

**Comment by ghost** [comment]
Hi @quanganh206,
No, if you use cordova cli 8.0 the plugin doesn't work because the directory structure of the project generated is different from the previous versions

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90,
You can run a Cordova application on Android Nougat (7.0) and Oreo (8.0) that's build with cordova-android 6.3.0 .
What error are you getting on Nougat?

I think @quanganh206 was talking about installing the platform with a specific version:
```
cordova platform add android@6.4.0
```

Other users have reported using this successfully with recent cordova client versions.

**Comment by jaimecbernardo** [comment]
Hi @quanganh206,

Could you please point me to a reference about the `minSdkVersion` having to be 26? I know the requirement is there for `targetSdkVersion`, but not for `minSdkVersion`.

If you need the `nodejs-mobile` library binaries built to another version of the SDK, it can be rebuilt to a different target API level by changing it here: https://github.com/janeasystems/nodejs-mobile/blob/9e90dd8c14fce5b047aa16d00e22a8ef44222a99/android-configure#L58

Regarding Flutter:

We're currently focusing on supporting cordova and react-native plugins, only, as these frameworks are built around the same language as the node runtime (JavaScript).
While there are no current plans for Flutter support, we're open to community contributions for supporting other frameworks and accept PRs.

Please let us know if you give it a try.

**Comment by ghost** [comment]
Hi  jaimecbernardo,
The topic of conversation is changing from my issue problem.
So, for a resume, specify me the right combination of the versions for every tool in order to use the cordova-mobile-nodejs plugin.

```
cordova-mobile-nodejs: 0.2.0
cordova cli: 7.0 ? 
cordova android platform: 7.1 ? 
targetSdkVersion: 26 API?
```

Check if the combination is right or we have to change something. After I will test with these versions.
Thanks

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,

Indeed the conversation is starting to get confusing. @haleminh , @quanganh206 , please create a new issue if your issue persists.

Everything seems good, except "cordova android platform". cordova android platform should be `6.3.0`, as you were using.

The issue you were having is due to a component on your Nexus 4 device, which is very old.

To see if your problem is coming from your component, I've pushed a branch to github for you to try. Here's a direct ling for the comment in case you missed it: https://github.com/janeasystems/nodejs-mobile/issues/105#issuecomment-412549133

To start the project from scratch but using the alternative module version that doesn't use ES6 JavaScript features, that your device doesn't seem to support, try to use the plugin like this:
```
cordova create hello com.example.hello HelloWorld
cd hello
cordova platform add android@6.3.0
cordova plugin add https://github.com/janeasystems/nodejs-mobile-cordova#staging-babel-UI-runtime
.\plugins\nodejs-mobile-cordova\install\sample-project\copy-sample-project.sh
cordova run android
```

This will use the plugin from a different branch in the github repo ( https://github.com/janeasystems/nodejs-mobile-cordova/tree/staging-babel-UI-runtime ).

**Comment by quanganh206** [comment]
Thanks @jaimecbernardo I will try.

Sorry to make confuse here @jaimecbernardo, good luck and happy coding.

**Comment by jaimecbernardo** [comment]
Thanks for bringing the concern to us, @quanganh206 .
Play Store compliance is important, since the plugin is supposed to be used in production, so please open a new issue if your problem persists.
Good luck and happy coding.

**Comment by ghost** [comment]
hi @jaimecbernardo;
I have installed the plugin with the babel javascript compiled:

```
cordova-mobile-nodejs:  https://github.com/janeasystems/nodejs-mobile-cordova/tree/staging-babel-UI-runtime
cordova cli: 7.0 
cordova android platform: 6.3.0
```

But the plugin seems not work. Here the log:

```
08-14 09:19:07.403 3723-3787/com.amanganiello90.angular D/NODEJS-CORDOVA: pluginInitialize
08-14 09:19:07.417 3723-3787/com.amanganiello90.angular V/NODEJS-CORDOVA: setAllChannelsListener
08-14 09:19:07.439 3723-3787/com.amanganiello90.angular D/NODEJS-CORDOVA: StartEngine: server.js
08-14 09:19:07.440 3723-3787/com.amanganiello90.angular D/NODEJS-CORDOVA: Script absolute path: /data/user/0/com.amanganiello90.angular/files/www/nodejs-project/server.js
08-14 09:19:07.779 3723-3800/com.amanganiello90.angular D/NODEJS-CORDOVA: Moving existing project folder to trash
    File not found: dir.list
    File not found: file.list
    Copying node project assets enumerating the APK assets folder
```

server.js is my node script that is found by plugin. But it wants dir.list and file.list files that I know what are they.

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90,
Those files are created by a hook that runs after `cordova prepare`: https://github.com/janeasystems/nodejs-mobile-cordova/blob/79092d967a1c6b35abd0f7b2f1dd436582f439ec/install/hooks/android/after-prepare-build-node-assets-lists.js

They are meant to make the copy faster on APIs where listing assets from the APK is a slow operation, but the runtime will fallback to using APK asset listing when those files are not available, so this error shouldn't be affecting your Cordova Application.

Are you using the usual workflow of running `cordova prepare android` for applying your changes to `www`?

Have you been able to verify the sample is running yet?

**Comment by ghost** [comment]
Thanks, now my app is running: https://github.com/amanganiello90/java-angular-web-app#cordova
