### ISSUE TITLE
Is it possible to create multiple listenner.

### ISSUE THREAD

**Issue by yankunsam** [janeasystems/nodejs-mobile#108]
* **Version**:
* **Platform**:
* **Subsystem**:

Because I need the different amount parameter for every listenref.

Thanks!

**Comment by jaimecbernardo** [comment]
Hi @yankunsam ,
I didn't understand your question. Are you using one of the plugins?
The node events API supports more than one listener.

**Comment by yankunsam** [comment]
Yes. I use it. I see the example. And try to add another listener named "account". But I can't get the right result.  Lik
```
nodejs.channel.addListener(
      'message',
      this.listenerRef,
      this
    );
```
I define 
```
nodejs.channel.addListener(
      'account',
      this.accountListener,
      this
    );
```

**Comment by jaimecbernardo** [comment]
Hi @yankunsam ,

There's only support for 'message' events, right now, for passing strings through the channel. Changes have been made to the Cordova plugin to support other event names, but these haven't been ported to the react-native plugin yet.

The current technique people have been using is passing messages as JSON strings through 'message' events and then calling different functions according to the type of the message.

I hope this is helpful.

**Comment by yankunsam** [comment]
Hi @jaimecbernardo . Yes, JSON strings is useful .   Thanks.
