### ISSUE TITLE
react native android run fail

### ISSUE THREAD

**Issue by Lizhooh** [janeasystems/nodejs-mobile#11]
I run the sample, and then compiled successfully, but the run failed

https://github.com/janeasystems/nodejs-mobile-samples

![dasda](https://user-images.githubusercontent.com/19299088/31329199-7e6e8b04-ad0b-11e7-86f3-6807c2b3968b.png)

* **Version**:  nodejs v8.5
* **Platform**:  win7 x64
* **Subsystem**: react native  android

**Comment by jaimecbernardo** [comment]
Hi @Lizhooh ,

Did you run `react-native link`?
It seems the Javascript portion of `nodejs-mobile-react-native` is unable to find a function that is defined in the native part.

In `SuspendResume/android/settings.gradle`, please verify that the `nodejs-mobile-react-native` lines are added. The file should look like this after running `react-native link`:
```
rootProject.name = 'SuspendResume'
include ':nodejs-mobile-react-native'
project(':nodejs-mobile-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/nodejs-mobile-react-native/android')

include ':app'
```

Hope this is helpful.

**Comment by Lizhooh** [comment]
Yes, I forgot, `link`.
After `link`, however, an unknown error occurred with the `react-native run-android`.
I don't know how to solve it.

look at the pictures.


![aaa](https://user-images.githubusercontent.com/19299088/31334927-eead0154-ad22-11e7-8e42-62859d87efe1.png)


**`gradlew clean` also failed.**


![1111](https://user-images.githubusercontent.com/19299088/31334960-07fff35a-ad23-11e7-81ba-d50a12737f56.png)

**Comment by jaimecbernardo** [comment]
From the log, I can see that it's not finding the NDK.

Have you tried opening the project in Android Studio to try and detect what prerequisites are not installed, [as suggested here?](https://github.com/janeasystems/nodejs-mobile-samples/tree/bf519d8366298db314b9225d7727b298b301f16e/react-native/SuspendResume#android) The NDK and CMake are prerequisites that should be installed with your Android SDK.

The sample also assumes you have a configuration as described in the `Building Projects with Native Code` section of [React Native's Getting Started page.](https://facebook.github.io/react-native/docs/getting-started.html)

Hope this is helpful.

**Comment by Lizhooh** [comment]
\\("▔□▔)/！
I have not installed `Android Studio`, I use `Visual Studio Code`.......

**Comment by Lizhooh** [comment]
@jaimecbernardo 
Thank, it has been successful.
