### ISSUE TITLE
ninja: error:  bin/x86/libnode.so', needed by cmake/debug/obj/x86/libnodejs-mobile-cordova-native-lib.so', missing and no known rule to make it

### ISSUE THREAD

**Issue by ghost** [janeasystems/nodejs-mobile#112]
Node Version: 8.x
Platform: linux/ubuntu

I have this error on my project in travis build when I execute ```cordova build android```:
```
 What went wrong:
Execution failed for task ':externalNativeBuildDebug'.
> Build command failed.
  Error while executing '/usr/local/android-sdk-25.2.3/cmake/3.6.4111459/bin/cmake' with arguments {--build /home/travis/build/amanganiello90/java-angular-web-app/cordova-app/app/platforms/android/.externalNativeBuild/cmake/debug/x86 --target nodejs-mobile-cordova-native-lib}
  ninja: error: '/home/travis/build/amanganiello90/java-angular-web-app/cordova-app/app/platforms/android/src/com/janeasystems/cdvnodejsmobile/jni/libnode/bin/x86/libnode.so', needed by '/home/travis/build/amanganiello90/java-angular-web-app/cordova-app/app/platforms/android/build/intermediates/cmake/debug/obj/x86/libnodejs-mobile-cordova-native-lib.so', missing and no known rule to make it
```

I use this platform:
cordova cli: 7.0.0
android platform: 6.3.0
mobile-nodejs-cordova: 0.2.1

The travis file is this:
```
 - language: android
      node_js: "8.x"
      env: 
        - JOB="ANDROID"
      android:
          components:
            - build-tools-27.0.3
            - tools
            - platform-tools
            - android-26
            - extra-android-m2repository
            - extra-google-m2repository
      before_install:
          - echo yes | sdkmanager "ndk-bundle"
          - echo yes | sdkmanager "cmake;3.6.4111459"
          - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
          - mkdir "$ANDROID_HOME/licenses" || true		
          - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"		
          - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install -y nodejs
      install:
- cd ./cordova-app/app && npm install && npm run preconfig && npm run build

```

In my project I have also the ```www/NODEJS_MOBILE_BUILD_NATIVE_MODULES_VALUE.txt``` with ```0```,
But I suppose that the feature to disable build native module is only for windows.

I replicated the issue on a linux machine of mine, and I noted that the  ```before-plugin-install.js``` hook is not executed correctly, because under  ```plugins/nodejs-mobile-cordova/libs/android/libnode/bin/x86```  I view ```libnode.so.gz``` instead of ```libnode.so```

**Comment by ghost** [comment]
I confirm. The error is on unzip of the  ```bin/x86/libnode.so.gz``` and ```bin/armeabi-v7a/libnode.so.gz``` . I have unzipped manually and the android build works.

Is it a bug?  Because the hook of ```before-plugin-install.js``` seems not working on linux.

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,

It should be unziped before the plugin installation, defined inside a cordova hook: https://github.com/janeasystems/nodejs-mobile-cordova/blob/79092d967a1c6b35abd0f7b2f1dd436582f439ec/plugin.xml#L59

If you are adding the plugin to the project in a custom way, it needs to be in such a way that it runs this hook. Examples of ways this is done successfully is by running `cordova plugin add nodejs-mobile-cordova` or `cordova prepare` (if the plugin entry is already in the app's `config.xml`, as in this sample: https://github.com/janeasystems/nodejs-mobile-samples/tree/master/cordova/UseNativeModules#how-to-run )

**Comment by ghost** [comment]
Hi,
The problem is in the ```cordova prepare``` phase. I have the plugin declared in the ```config.xml``` app, but seems that the hook is called only with the ```cordova plugin add ...``` command 


UPDATE:
```cordova prepare``` works if the plugin is defined in the ```config.xml``` and the cordova root project doesn't have platforms and plugins folders

**Comment by jaimecbernardo** [comment]
Yes, if you were only using `npm install` for installing the cordova plugins, the hooks wouldn't be run. `cordova prepare` is the recommended way to do this for Cordova applications.

**Comment by ghost** [comment]
Hi,
 the ```npm install``` is the first step before using every cordova command. The issue is that the hook is not called in the ```cordova prepare``` if your cordova project has  ```platforms and plugins``` folders not empty.

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,
`cordova prepare` runs `npm install` as well as the hooks. Have you tried running `cordova prepare` before `npm install`?

**Comment by ghost** [comment]
Hi @jaimecbernardo,
The ```cordova prepare``` performs the npm install only for default scripts and dependencies. If you have some custom dependencies or scripts in your package.json, it doesn't install that things in node_modules folder

**Comment by jaimecbernardo** [comment]
I see.
`npm install` won't run the Cordova hooks, so it's not the best way to install the cordova plugins into a project.

For your specific case, how about running `npm install` after `cordova prepare`?
So, instead of:
```
cd ./cordova-app/app && npm install && npm run preconfig && npm run build
```
it would be:
```
cd ./cordova-app/app && cordova prepare && npm install && npm run preconfig && npm run build
```

**Comment by ghost** [comment]
Hi @jaimecbernardo,
The ```cordova prepare``` is run in ```npm run build``` script. ```npm install``` is performed in order to install custom dependencies that I have  included in the ```package.json```

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,
I think that would not be a correct way for installing the cordova dependencies, then, as it doesn't run the hooks.
I'd advise you to check the Cordova documentation to understand how to install plugins in such a way that the hooks will execute, then. One possible way might be to add an appropriate command that will run the hooks to your `npm run build` script, since your project has these custom needs.

I hope this is helpful.

**Comment by ghost** [comment]
Hi @jaimecbernardo,
you didn't understand the use case. I will explain the issue solution with the following summary in **two considerations**.

**First**: The hook of ```plugin_install``` is called when you add a plugin or if you perform ```cordova prepare``` when your root project has the ```config.xml``` with the plugin already added and **you don't have ```platforms``` and ```plugins``` folders**. 

**Second**: The ```cordova prepare``` command executes also the ```npm install``` only for the default dependencies, but if you have for example a ```package.json``` as:

```
{
    "name": "com.amanganiello90.angular",
    "displayName": "angularDashFullStack",
    "version": "1.0.0",
    "description": "A sample Apache Cordova application to integrate nodejs full app.",
    "main": "index.js",
    "scripts": {
        "build": "cordova prepare android && cordova build android",
        "start": "cordova prepare android && cordova run android",
        "preconfig": "cd ./www/nodejs-project && npm install"
    },
    "author": {
        "name": "Angelo Manganiello",
        "email": "angelo.mang@libero.it"
    },
    "license": "Apache-2.0",
    "devDependencies": {
        "cpx": "1.5.0",
        "cordova": "7.0.0"
    },
    "dependencies": {
        "cordova-android": "6.3.0",
        "cordova-plugin-whitelist": "1.3.3"
    },
    "cordova": {
        "plugins": {
            "nodejs-cordova-plugin": {}
        },
        "platforms": [
            "android"
        ]
    }
}

```
The ```cordova prepare``` doesn't create a ```node_modules``` with the ```cpx``` and ```cordova``` devDependencies (that are dependencies added manually by the developer and not by the ```cordova cli```). So in this case you have to run ```npm install``` also.

Now is it clear?

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,
I think I got it clearly. What's the issue with this workaround I proposed a few messages back?
`cd ./cordova-app/app && cordova prepare && npm install && npm run preconfig && npm run build`

**Comment by ghost** [comment]
Hi @amanganiello90 ,
In your command: 
```
cd ./cordova-app/app && cordova prepare && npm install && npm run preconfig && npm run build
```
The running of ```cordova prepare``` is unuseful because ```npm run build``` performs this.

So it's correct writing:

```
cd ./cordova-app/app &&  npm install && npm run preconfig && npm run build
```

In summary this github issue is resolved, because the plugin works (and the hook) with:

```
cordova plugins add nodejs-mobile-cordova
```
(after adding android platform)

or
```
cordova prepare
```
(after adding platform, plugin and deleted platforms and plugins folders)

The issue is closed.
