### ISSUE TITLE
Unable to sync data between multiple peers

### ISSUE THREAD

**Issue by mavericksthinker** [janeasystems/nodejs-mobile#118]
* **8.10**:
* **Ubuntu 18.04(unix)**:
* **Nodejs for cordova android**:

I am implementing nodejs for cordova and was able to make the nodeserver start on my cordova android app , I am using Gun to store the data in the database , but the problem that I am facing is that I am unable to sync the data entered at one peer(client) with the other peer(client) connected to the same local network . Can I get any suggestion of how to achieve that using nodejs for cordova . I have a Gun server that when is running the cordova android app clients are able to connect to the server and sync data among themselves 
                                         
               const fs = require('fs');
               var config = {
	           port: process.env.OPENSHIFT_NODEJS_PORT || process.env.VCAP_APP_PORT || 
                process.env.PORT || process.argv[2] || 8765
               };
                const Gun = require('gun')

               if(process.env.HTTPS_KEY){
	       config.key = fs.readFileSync(process.env.HTTPS_KEY);
	       config.cert = fs.readFileSync(process.env.HTTPS_CERT);
	       config.server = require('https').createServer(config, Gun.serve(__dirname));
               } else {
	       config.server = require('http').createServer(Gun.serve(__dirname));
               }

               var gun = Gun({	
	          file: './gun/server1',
	          web: config.server
                });

                config.server.listen(config.port);
                console.log('Server started on port ' + config.port + ' with /gun');

and it is working seemlessly . But when I am trying to integrate it in the nodejs for cordova .The app is storing the data locally but they are unable to communicate with the other peer(client with nodejs running in their background) to sync data among eachother that are connected to the same local network.
I am just trying this with the basic examples

INDEX.HTML file
-------------------------
                   <form>
    <input><button>Add</button>
                   </form>

                  <ul></ul>
                  <script type="text/javascript" src="cordova.js"></script>
                  <script type="text/javascript" src="js/index.js"></script>
                  <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
                  <script src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>
                  <script>
				var gun = Gun().get('thoughts');
				$('form').on('submit', function(event){
					event.preventDefault();
					gun.set($('input').val());
					$('input').val("");
				});
				gun.map().on(function(thought, id){
					var li = $('#' + id).get(0) || $('<li>').attr('id', id).appendTo('ul');
					if(thought){
						$(li).text(thought);
					} else {
						$(li).hide();
					}
				});
				$('body').on('dblclick', 'li', function(event){
					gun.get(this.id).put(null);
				});
        </script>
    </body>
</html>

MAIN.js
------------
                 // Require the 'cordova-bridge' to enable communications between the
                // Node.js app and the Cordova app.
                    const cordova = require('cordova-bridge');
                    const fs = require('fs');
                     var config = {
	             port: process.env.OPENSHIFT_NODEJS_PORT || process.env.VCAP_APP_PORT || 
                     process.env.PORT || process.argv[2] || 8765
                     };
                   const Gun = require('gun');
                   if(process.env.HTTPS_KEY){
	           config.key = fs.readFileSync(process.env.HTTPS_KEY);
	           config.cert = fs.readFileSync(process.env.HTTPS_CERT);
	           config.server = require('https').createServer(config, Gun.serve(__dirname));
                   } else {
	           config.server = require('http').createServer(Gun.serve(__dirname));
                    }
                   var gun = Gun({
                   file:"*",
                   web: config.server,
                    radisk: false,
                    localStorage:true,
                   //peers: ['http://***.***.***.***:3000/gun'] //add this line
                     });
                   // Send a message to Cordova.
                  cordova.channel.send('main.js loaded');

                  // Post an event to Cordova.
                  cordova.channel.post('started');

                    // Post an event with a message.
                   cordova.channel.post('started', 'main.js loaded');

                   // A sample object to show how the channel supports generic
                   // JavaScript objects.
                   class Reply {
                   constructor(replyMsg, originalMsg) {
                    this.reply = replyMsg;
                   this.original = originalMsg;
                    }
                   };

                  // Listen to messages from Cordova.
                  cordova.channel.on('message', (msg) => {
                  console.log('[node] MESSAGE received: "%s"', msg);
                   // Reply sending a user defined object.
                  cordova.channel.send(new Reply('Message received!', msg));
                   });

                  // Listen to event 'myevent' from Cordova.
                    cordova.channel.on('myevent', (msg) => {

                    gun.get('thought').once((data)=>{return data;});
                    config.server.listen(config.port);
                    console.log('Server started on port ' + config.port + ' with /gun');
                    console.log('[node] MYEVENT received with message: "%s"', msg);
                     });

                    // Handle the 'pause' and 'resume' events.
                    // These are events raised automatically when the app switched to the
                    // background/foreground.
                       cordova.app.on('pause', (pauseLock) => {
                       console.log('[node] app paused.');
                       pauseLock.release();
                        });

                        cordova.app.on('resume', () => {
                        console.log('[node] app resumed.');
                         cordova.channel.post('engine', 'resumed');
                         });

Any help will be deeply appreciated. Thank you.

**Comment by jaimecbernardo** [comment]
Hi @mavericksthinker ,

I'm not familiar with gun, but I guess this issue is more about using that modules than about nodejs-mobile, so I think the best strategy would be to look into the way to sync between peers in gun. You'll probably have to find a way to look for peers in the local network so that they can identify each other (UDP broadcast might be way to achieve this).

From the code you posted it seems there might be a peer array you'll have to manipulate at runtime. Look at this commented line from the code you posted: 
```
//peers: ['http://***.***.***.***:3000/gun'] //add this line
```

This doesn't seem to be a "nodejs-mobile" issue. My advice would be to first trying to develop this node project on different Desktop machines as peers in the same local network with gun so that you can get a better understanding of how it'd work and then porting it to the mobile application.

I hope this is helpful.

**Comment by mavericksthinker** [comment]
Actually I have also tried it with pouchdb which is also implemented [here](https://github.com/janeasystems/node-mobile-react-demo). I just want the [same logic](https://youtu.be/8Wx0kxWpvkY) to be implemented on cordova android app with pouchdb. 
Or as each device that has the app will serve as a server(running in the background of the client), can a sample implementation be provided to communicate within two or more of those manually using nodejs plugin for cordova ?

**Comment by jaimecbernardo** [comment]
Hi @mavericksthinker,

Indeed, each device will have a server running, so they'll have to have a way to discover each other for them to sync up. On the case of the pouchdb sample for iOS, the strategy used was UDP broadcast.

**Comment by arminsal1** [comment]
@mavericksthinker I'm trying to get Gun to work with this library too. Did you manage to figure out the peer situation?
