### ISSUE TITLE
BUILD ERROR: Unexpected identifier 'str'

### ISSUE THREAD

**Issue by aerielcruz** [janeasystems/nodejs-mobile#122]
# A continuation of https://github.com/janeasystems/nodejs-mobile/issues/120

* **Project**: nodejs-mobile-react-native
* **Version**: v0.3.0
* **Mobile device**: Android
* **Mobile OS and version**: Oreo
* **Development Node.js**: v10.9.0
* **Development platform**: Darwin Kernel Version 17.7.0
* **Build Gradle version**: 3.1.4
* **Gradle version**: 4.4

## Output
<img width="402" alt="screen shot 2018-09-20 at 3 05 04 pm" src="https://user-images.githubusercontent.com/31103697/45801514-a9ad3180-bce6-11e8-873a-92ed1b93cd2e.png">

## Build error even if "BUILD SUCCESSFUL"
**What I found that may have been the cause while building/running `react-native run-android`**
```
> Task :nodejs-mobile-react-native:GenerateNodeProjectAssetsLists UP-TO-DATE
A problem was found with the configuration of task ':nodejs-mobile-react-native:GenerateNodeProjectAssetsLists'. 
Registering invalid inputs andoutputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - File '/Users/username/Project/android/build/nodejs-assets' specified for property '$1' is not a file.
```
Also tried this [solution](https://stackoverflow.com/questions/36540676/build-intermediates-res-resources-anzhi-debug-stripped-ap-specified-for-prope) where I change build gradle version to `2.1.3` but when I try to build it, it was looking for `implementation` method for `:nodejs-mobile-react-native` in `build.gradle` so I've change 
```
compile project(':nodejs-mobile-react-native')
to
implementation project(':nodejs-mobile-react-native')
```
And it still gave me the same error so I went back to build gradle `3.1.4` and tried `./gradlew clean` but didn't work either.
It may have to do something about `shrinkResources` and `minifyEnabled` but I'm not sure.
## To reproduce issue
Just follow this https://github.com/janeasystems/nodejs-mobile/issues/120#issue-361440229 then add the `rn-cli.config.js` file by @jaimecbernardo [solution](https://github.com/janeasystems/nodejs-mobile/issues/120#issuecomment-422886530)
then run `react-native run-android`

**Comment by aerielcruz** [comment]
## Solved!
**Looked at the wrong problem. This is another output that was shown while building.**
```
adb server version (40) doesn't match this client (39); killing...
* daemon started successfully *
```
The issue was the `adb` version mismatch and the PATH issue where if you've installed it through `brew` then it has it's own `adb` path so all I need to do was to direct it to Android sdk's path.
```
$ export PATH="/Users/username/Library/Android/sdk/platform-tools:${PATH}"
```
Solution was found [here](https://github.com/expo/expo/issues/180#issuecomment-318928170). Basically just export the path.

**Comment by jaimecbernardo** [comment]
Good to know it was solved. This is part of the react-native instructions for "Building Projects with Native Code" stated here: https://facebook.github.io/react-native/docs/getting-started#3-configure-the-android-home-environment-variable

> Add the following lines to your $HOME/.bash_profile config file:
> ```
> export ANDROID_HOME=$HOME/Library/Android/sdk
> export PATH=$PATH:$ANDROID_HOME/tools
> export PATH=$PATH:$ANDROID_HOME/tools/bin
> export PATH=$PATH:$ANDROID_HOME/platform-tools
> export PATH=$PATH:$ANDROID_HOME/emulator
> ```
