### ISSUE TITLE
FileNotFoundException: nodejs-project/node_modules/optimist/test/_/bin.js

### ISSUE THREAD

**Issue by Eljoy** [janeasystems/nodejs-mobile#128]
While trying to run the project on an emulated device I faced the following error:

`Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/optimist/test/_/bin.js
                      at android.content.res.AssetManager.openAsset(Native Method)`

The bin.js exists.

**Comment by Eljoy** [comment]
Resolved. Access rights related issue.

**Comment by jaimecbernardo** [comment]
Hi @Eljoy ,
Good to know.
Some runtime errors might also occur due to the path starting with an underscore. Check this issue for more information: https://github.com/janeasystems/nodejs-mobile/issues/60
