### ISSUE TITLE
Build nodejs-mobile-react-native failed

### ISSUE THREAD

**Issue by ferologics** [janeasystems/nodejs-mobile#130]
* **Project**: nodejs-mobile-react-native
* **Version**: 0.3.0
* **Mobile device**: simulator/emulator Android Nexus 6P
* **Mobile OS and version**: Android 8.0
* **Development Node.js**: v9.11.2
* **Development platform**: TBD

### Issue

When running `$ react-native run-android` the build fails with following error:

>libnode/bin/_x86_64/libnode.so needed by ... missing and no known rule to make it.

![f7213b0f-3300-43f2-8213-274b8cf5064d](https://user-images.githubusercontent.com/5576161/46464716-4f709e00-c7c7-11e8-8d0e-fb4e222bf229.png)

**Comment by jaimecbernardo** [comment]
Hi @ferologics ,
Have you managed to solve the issue in the meanwhile?

**Comment by ferologics** [comment]
I had to downgrade Java, or set Node to 9.x.y, one of the two. Deprecated dependencies that work under the lower version, but break in latest builds.

**Comment by rdchua** [comment]
@ferologics may i know what version of node you used? I used 9.9.0 but stil did not work

**Comment by eddyjusufi** [comment]
@jaimecbernardo I am also getting this error when running `react-native run-android`. Neither downgrading to Java 1.8 nor downgrading to Node 9.0.0 helped me solve this. Any help would be appreciated.

**Comment by jaimecbernardo** [comment]
Hi @EddieEJ,
This is likely caused by the plugin not having the 64 bit binaries. The 3.3.0 version was published with the 64 bit binaries:
https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.3.3

Would you mind giving it a try?

**Comment by eddyjusufi** [comment]
> Hi @EddieEJ,
> This is likely caused by the plugin not having the 64 bit binaries. The 3.3.0 version was published with the 64 bit binaries:
> https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.3.3
> 
> Would you mind giving it a try?

@jaimecbernardo I have just updated to the new version and I can confirm that running `react-native run-android` is working as perfect as expected now and will not result in getting that error anymore.

Thank you!
