### ISSUE TITLE
Cannot access node HTTP server from the device connected to the same local network

### ISSUE THREAD

**Issue by dongzhi** [janeasystems/nodejs-mobile#135]
* **Project**: nodejs-mobile iOS Getting Started example
* **Version**: "mobile":"0.1.7"
* **Mobile device**: iPhone 6 and  iPhone 7
* **Mobile OS and version**: iOS 12.0
* **Development Node.js**: "node":"8.6.0"
* **Development platform**: macOS Mojave 10.14 + Xcode Version 10.0 (10A255)

Hi,  I am following iOS native-xcode example: [https://code.janeasystems.com/nodejs-mobile/getting-started-ios](url).  The example app can be created and successfully runs on the iOS device, but I cannot access the HTTP server( `IP:10.0.0.2` ) from my Mac( `IP:10.0.0.5` ) connected to the same local network. 

<img width="1116" alt="1" src="https://user-images.githubusercontent.com/477388/47009292-b8182d00-d16e-11e8-885a-9b52f4b4ab36.png">

From Xcode Network Report, it seems that iOS has received the TCP packet.

<img width="948" alt="2" src="https://user-images.githubusercontent.com/477388/47009279-acc50180-d16e-11e8-8635-d43ce53c970a.png">

However,  the same HTTP server can be reached through Bonjour link-local address( `http://iphone.local:3000` ):

<img width="1035" alt="3" src="https://user-images.githubusercontent.com/477388/47009791-ee09e100-d16f-11e8-96ff-b1e2705654e5.png">

I also tried different routers and iPhones. No luck. I was wondering if it's related to iOS security restrictions or it's just a bug of nodejs-mobile. 

Hope I could get some help to resolve this issue. Thanks in advance!

**Comment by jaimecbernardo** [comment]
Hi @dongzhi ,

It's possible that the server is not listening on all interfaces, so you might have to try to listen on specific interfaces: https://nodejs.org/docs/latest-v8.x/api/net.html#net_server_listen_port_host_backlog_callback

Reading the docs and printing more information about the state of the server and network interfaces might be helpful in figuring out what is happening.

```
var http = require('http');
var os = require('os');
var versions_server = http.createServer( (request, response) => {
    response.end('Versions: ' + JSON.stringify(process.versions) +
                 ' listening on' + JSON.stringify(versions_server.address()) +
                 ' interfaces are ' + JSON.stringify(os.networkInterfaces()));
    });
versions_server.listen(3000);
```

**Comment by dongzhi** [comment]
Hi @jaimecbernardo,

Thanks for your reply. I figured it out. It's actually caused by [a region-specific function/bug of iOS](https://apple.stackexchange.com/questions/278051/ios-10-wi-fi-is-turned-off-for-some-application-and-cannot-turn-on). Ever since iOS 10, Apple requires Chinese model iPhones to choose Internet data access for each application(both WLAN and cellular, not just cellular data access like the US model). For most applications which require networking, a dialogue will show up asking for data access permission. like this:

<img width="367" alt="4" src="https://user-images.githubusercontent.com/477388/47092098-ce021c80-d258-11e8-8f7c-5cc4b5dc3bf6.png">

However, in my case, the example application doesn't request any url therefore this dialogue never pops out and iOS turns off the WiFI&cellular data access completely which causes my problem.

Since iOS hasn't provided any API to programmatically request this permission, my workaround is to create a NSURLRequest to trigger the dialogue when the app starts. Then everything works as expected. 

I will close this issue as it's not `nodejs-mobile`'s fault. Thx again for the great project. 🍻🍻🍻

**Comment by jaimecbernardo** [comment]
Thank you for the explanation! This was a quirk I was not aware of.
