### ISSUE TITLE
Can't import 'net' module

### ISSUE THREAD

**Issue by roman-zaiats** [janeasystems/nodejs-mobile#140]
Having an issue with not importing 'net' module.

All other modules seem to be imported correctly. Only 'net' is be missing.
What I'm doing wrong?

`const net = require('net');`

net = undefined

**Comment by jaimecbernardo** [comment]
Hi @approce ,
This is not a known issue.
You've closed the issue right away, so I'm assuming it was solved.
Would you mind giving more information on what was causing the issue for you?
Thank you, in advance.
