### ISSUE TITLE
Release-universal NodeMobile.framework unsupported achitectures [x86_64]

### ISSUE THREAD

**Issue by mdfalcon104** [janeasystems/nodejs-mobile#144]
While I submit my iOS app to App Store, I got this bug.

<img width="742" alt="screen shot 2018-11-10 at 10 12 17 pm" src="https://user-images.githubusercontent.com/5404685/48302964-8bb9bb80-e536-11e8-9e4f-6e0986e5631b.png">

**Comment by jaimecbernardo** [comment]
Hi @dlpigpen ,

This issue seems relevant to your case: https://github.com/janeasystems/nodejs-mobile/issues/30
Have you tried it?

This information can also be found in the README:
> While the universal framework is useful for faster Application development, due to supporting both iOS devices and simulators, frameworks containing simulator strips will not be accepted on the App Store. Before trying to submit your application, it would be advisable to use the Release-iphoneos/NodeMobile.framework in your submission archive or strip the x64 slices from the universal framework's binaries before submitting.

**Comment by mdfalcon104** [comment]
@jaimecbernardo 
Thank for your answer. I downloaded the newest framework [Node.js for Mobile Apps core library v0.1.8](https://github.com/janeasystems/nodejs-mobile/releases/tag/nodejs-mobile-v0.1.8). This issue gone away.
