### ISSUE TITLE
Incomplete documentation: Building for Android

### ISSUE THREAD

**Issue by paramtatv** [janeasystems/nodejs-mobile#147]
Hi,

Can you please elaborate for what do we need after generating the libnode.so for Android. Documentation is very thin and unclear for new developers.

Please help

**Comment by jaimecbernardo** [comment]
Hi @tim-coin ,
Please refer to https://github.com/janeasystems/nodejs-mobile/tree/f1e5e5ad5e90ac4b3f2e7782b3dd39ca139ff5b7#resources-for-newcomers

The Website has a Getting Started section for Android Apps where that is explained.

**Comment by paramtatv** [comment]
I can see that the toolchain is used for clang++
Thanks
