### ISSUE TITLE
NodeJS Version

### ISSUE THREAD

**Issue by nickyromeijn** [janeasystems/nodejs-mobile#15]
What version of node does nodejs-mobile use? I'm running into some issues regarding modules that require a specific version of node. 

If it's 8+ is it possible to define your own version of node to use?

**Comment by jaimecbernardo** [comment]
Hi @nickyromeijn ,
Thanks for the issue.

We are currently using `node-chakracore` v8.4.0 for `nodejs-mobile`: https://github.com/janeasystems/nodejs-mobile/releases/tag/nodejs-mobile-v0.1.2

What sort of issues are you running into?

I can't think of a way to define the version of node you want to run. Is this a feature I'm unaware of?

**Comment by nickyromeijn** [comment]
Hello @jaimecbernardo 

This can be closed. I was trying to use a node6 module which didn't work it's fixed now :)

**Comment by jaimecbernardo** [comment]
Hello @nickyromeijn 
Good to hear. I'm closing it, then. Thank you.
