### ISSUE TITLE
Build error at cmake

### ISSUE THREAD

**Issue by mavericksthinker** [janeasystems/nodejs-mobile#160]
* **Hybrid App**:
* **BableUI**:
* **Cordova -Android**:
* **Android and 21**:
* **8.12**:
* **UBUNTU**:

I am building a cordova project which requires cmake for building the native modules for android. Everything was working well and the build was successful but after upgrading the cmake to 3.10.2 on android studio I am getting this error.

What went wrong:

    Execution failed for task ':generateJsonModelDebug'. > Error occurred while communicating with CMake server. Check log /home/hottab/Documents/Cordovaapps/pos/platforms/android/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_server_log.txt for additional information.

 cmake_server_log.txt
------------------------------
     CMAKE SERVER:   CMAKE SERVER: [== "CMake Server" ==[  CMAKE SERVER: {"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}  CMAKE SERVER: ]== "CMake Server" ==] 

 I have tried to downgrade it to 3.6.0 ,3.6.2 and 3.6.3 but the problem persisted. My previous version that I checked on android studio was 3.6.4111459 . When I am downloading cmake via android studio its currently downloading 3.10.2. Is there any way that this problem can be solved. any help will be deeply appreciated. I have seen other questions but none of the method worked.

**Comment by jaimecbernardo** [comment]
Hi @mavericksthinker ,

Thank you for reporting this.

Looks like that's an experimental version. When I open the SDK Manager in Android Studio and Check `Show Package Details` in the `SDK Tools` tab, I'm still able to chose between `3.10.2.4988404` and `3.6.4111459`.
Is this option available to you when checking the `Show Package Details` option and expanding `CMake`?

**Comment by mavericksthinker** [comment]
Yes I have tried that and initially I had the same problem but after uninstalling the cake entirely form the system and installing Cmake 3.6.4111459 using Android studio . Solved the issue . But with Android studio 3.3 the sync fails with npm exit with code 1

**Comment by jaimecbernardo** [comment]
Hi @mavericksthinker ,
Thanks for reporting this. I'm on Android Studio 3.3 but this specific issue doesn't occur to me (it's on macOS, though, not on Linux).
Does trying to run from the Command Line give you more information?
`cordova run android` or `cd platforms/android && ./gradlew assembleDebug` might give you more information of what might be wrong.
Running `gradlew` with the flags it recommends after running the first time might also be useful: `./gradlew assembleDebug --stacktrace`

**Comment by mavericksthinker** [comment]
Yes I have tried to do that but it doesn't give anymore detail about it. It's because cmake 3.7 introduced cmake server which is causing problem . Degrading cmake to 3.6 solve this issue for now.

**Comment by mavericksthinker** [comment]
Issue #161 gives an overview and a way to build on Android studio 3.3. So closing the issue
