### ISSUE TITLE
Gradle sync fails in android studio

### ISSUE THREAD

**Issue by RIPT1DE** [janeasystems/nodejs-mobile#161]
* **Project**: nodejs-mobile-react-native
* **Version**: 0.3.2
* **Mobile device**:  n/a
* **Mobile OS and version**: n/a
* **Development Node.js**: 10.11.0
* **Development platform**: Windows 10, 1809, 64 bit
My android studio version is 3.3, with latest ndk(18) and android sdk 27 installed
I have already created react native project, added and linked the node js-mobile module. When i open the android folder in Android Studio, it starts syncing automatically, but then the sync fails with the error: SIMPLE: Error configuring
idea.log is attached
[idea.log](https://github.com/janeasystems/nodejs-mobile/files/2767840/idea.log)

**Comment by mavericksthinker** [comment]
I faced the similar problem with my project downgrading to Android studio 3.2.1 solves the issue for me .But it will be better to know why the sync fails in Android studio 3.3

**Comment by jaimecbernardo** [comment]
Hi @RIPT1DE ,
Please try building it from the command line, using `react-native run-android` to see if it gives more useful information about why Gradle seems to fail.

**Comment by RIPT1DE** [comment]
@mavericksthinker thanks, I'll try that

**Comment by RIPT1DE** [comment]
@jaimecbernardo 
> Hi @RIPT1DE ,
> Please try building it from the command line, using `react-native run-android` to see if it gives more useful information about why Gradle seems to fail.

Hi, heres the output from that command:
[log.txt](https://github.com/janeasystems/nodejs-mobile/files/2784163/log.txt)

Edit:
read through the log once again, realized that a program called "ninja" is required... so i installed it, and it builds!!!!. After that there were some permission problems, so i switched from yarn(default in react native) to npm and it works!!! Closing issue now, thanks for your help @jaimecbernardo

**Comment by jaimecbernardo** [comment]
It seems CMake server depends on ninja being installed in the system. Thank you for sharing the solution.
