### ISSUE TITLE
Permissions error when creating file.

### ISSUE THREAD

**Issue by andreddosantos** [janeasystems/nodejs-mobile#162]
Hi guys 

I'm using nodejs-mobile-cordova in an Ionic 4 app, all smooth until i tried to create a new file using the package 'fs'.

Error:
> EACCES: permission denied, open '/storage/0123-4567/folder1/mynewfile1.txt'

Code:
```
fs.appendFile(uri + 'mynewfile1.txt', 'Hello content!', function (err) {
if (err) throw cordova.channel.send("fs error: " + err.message);
cordova.channel.send("FS: sample file created")
});
```

- The path exists;
- I'm serving and reading files from the specific folder.
- Permissions in manifest:
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

The ideia is to use the nodejs-mobile-cordova  as local api serving data from a sqlite db, I'm not being able to create the db file, so i've decided to make a test by trying to create a new txt file with the 'fs' package and found this permission issue.

Can someone help?
Regards
André Lopes Santos

**Comment by andreddosantos** [comment]
Well when using this path "cordova.app.datadir()" all works, but i really wanted to be able to write on the External SDCard.

Any solution?
Best Regards

**Comment by jaimecbernardo** [comment]
Hi @andreddosantos ,
You've closed the issue, so I'm assuming you've been able to solve your problem.
Could you please share what was causing this behavior in your case? :)

**Comment by andreddosantos** [comment]
I'm using "cordova.app.datadir()" where i'm allowed to read and write data. It would be great if i could use the sdcard also, but for now this approach also works for me.

**Comment by andreddosantos** [comment]
Hello @jaimecbernardo with the[ Diagnostic plugin ](https://ionicframework.com/docs/native/diagnostic) using the method [getexternalsdcarddetails](https://github.com/dpa99c/cordova-diagnostic-plugin#getexternalsdcarddetails) it returns two directory entries one is root and the other is your application external root folder. I was trying to write in the root of the sdcard, now when writing on the app directory it works! 

Thanks for the support

**Comment by export-mike** [comment]
@andreddosantos unrelated to the issue but notice you're running sqlite and storing to the FS, hows that working out for you?
