### ISSUE TITLE
My solution: something about cordova android 7 not support

### ISSUE THREAD

**Issue by dingo1220** [janeasystems/nodejs-mobile#168]
my project use:

    "cordova-android": "^7.1.4",

    "nodejs-cordova-plugin": "^2.1.0", [like a fork of this project(janeasystems/nodejs-mobile)]

and get some errors. when building, running.

here is my solution.

in this file:
platforms/android/nodejs-cordova-plugin/projectname-build.gradle

change 3 lines.
from:
src/com/janeasystems/cdvnodejsmobile/jni
to:
src/main/src/com/janeasystems/cdvnodejsmobile/jni

that's it.

Now my nodejs run on my android device

something else...

Cordova version 8 is ok. it just use cordova-android 7 by default. this can change to 6 by this:
cordova platform add android@6

Cordova version 7 is ok by default. it just use cordova-android 6 by default.

**Comment by jaimecbernardo** [comment]
Hi @dingo1220 ,

Thank you for sharing it.

Indeed the issues with `cordova-android 7.x` are with the project structure. Using a `cordova-android 6.x` project structure can let you use newer versions of cordova, as described in other issues: https://github.com/janeasystems/nodejs-mobile/issues/48#issuecomment-366858320

There are plans to bring better support for more recent versions of cordova (while fully testing them in depth), which include supporting the new project structure.

**Comment by jaimecbernardo** [comment]
Hi @dingo1220 ,
We've released an update to bring support to more recent `cordova-android` versions: https://www.npmjs.com/package/nodejs-mobile-cordova/v/0.2.4
Please give it a try.
