### ISSUE TITLE
Nodejs-mobile in Android library project?

### ISSUE THREAD

**Issue by martijnvdwoude** [janeasystems/nodejs-mobile#170]
Has anyone here tried and succeeded to move nodejs-mobile into a Android library project and use it in a different project?

I refactored the `native-gradle-node-folder` example and changed it to a Android libary `apply plugin: 'com.android.library'`.  Then in my main project I'm trying to include this project.

However I'm running into this error until I run out of memory:

`14:41:08.454 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService]  Build operation root.1.64.14373 could not be started (4 worker(s) in use).`

Am I missing some things here? The library project with nodejs-mobile syncs fine with Gradle.

**Comment by jaimecbernardo** [comment]
Hi @martijnvdwoude ,

Haven't tried it yet. I guess the most promising refactoring strategy would be some sort of gradle integration, like the cordova and react-native plugins do.

Do you have a repo you could share?

**Comment by martijnvdwoude** [comment]
As I was preparing an example repo I found out that it worked just fine as a library project in a new project but not in our app, as I encountered the error above.

Turns out in my case I needed to increase the amount Gradle workers with `org.gradle.workers.max`, have it at 16 now. 

I guess you learn something new about Gradle every day! This issue can be closed now.

**Comment by jaimecbernardo** [comment]
Hi @martijnvdwoude ,
That's nice!
In any case, please consider sharing your method (or a repo with this method), as it'd be helpful for other users trying the same. 😄
