### ISSUE TITLE
react-native link unable to find android module

### ISSUE THREAD

**Issue by eddyjusufi** [janeasystems/nodejs-mobile#179]
I have just used `react-native init ProjectName` to set up a vanilla project on latest react-native version (currently `0.59.1`). After initialising it, I ran the project on both iOS and Android and everything worked fine.

After running `npm install`, trying to link [`react-native link nodejs-mobile-react-native`] gives me this output:
![error](https://user-images.githubusercontent.com/25306489/54401892-613d6200-46d2-11e9-876a-9973d755ed63.png)

Has anyone encountered this issue and know what might be causing this?

**EDIT:**
When initialising a project with react-native version `0.58.4` I do not get this linking issue.

**Comment by jaimecbernardo** [comment]
Hi @EddieEJ,

Thank you for reporting it.
It's caused by change in paths inside react-native.
There's a PR for this already: https://github.com/janeasystems/nodejs-mobile-react-native/pull/8
Looking into it.

**Comment by unmec** [comment]
Please see https://github.com/janeasystems/nodejs-mobile-react-native/pull/8#issuecomment-473513102

**Comment by jaimecbernardo** [comment]
Hi @EddieEJ ,

The fix for this issue was released in https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.3.4
Please give it a try.

**Comment by eddyjusufi** [comment]
@jaimecbernardo Everything seems to be working now. Thank you!
