### ISSUE TITLE
Set APP_PLATFORM according to minSdkVersion

### ISSUE THREAD

**Issue by staltz** [janeasystems/nodejs-mobile#188]
This issue is a continuation of #182. I solved that issue by simply lowering the `targetSdkVersion` to `23`. But [Google Play is strictly enforcing](https://developer.android.com/distribute/best-practices/develop/target-sdk) app updates to use `targetSdkVersion = 26` today, and in November 1st, enforcing `targetSdkVersion = 28`. To my app this would mean that users updating from Google Play would experience the #182 runtime crash if they have an older Android version.

If it's possible, we could change nodejs-mobile to set APP_PLATFORM (ndk-build) and ANDROID_PLATFORM (CMake) according to `minSdkVersion` and not `targetSdkVersion`, as [this document recommends](https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#target-api-set-higher-than-device-api), if possible.

**Comment by jaimecbernardo** [comment]
Hi @staltz ,

This change makes sense.
We'll give it a try changing https://github.com/janeasystems/nodejs-mobile-react-native/blob/022c47e67f298d89170aea8e7b5e31103f433ebb/android/build.gradle#L339 to use `minSdkVersion` instead of `targetSdkVersion`.

**Comment by staltz** [comment]
> We'll give it a try changing https://github.com/janeasystems/nodejs-mobile-react-native/blob/022c47e67f298d89170aea8e7b5e31103f433ebb/android/build.gradle#L339 to use minSdkVersion instead of targetSdkVersion.

I tried this out and it worked. :+1:

**Comment by jaimecbernardo** [comment]
Thanks for letting me know.
I've applied a fix for this: https://github.com/janeasystems/nodejs-mobile-react-native/commit/bb9313234715472229e16907f567deb95174f56b
It's been released to npm as well: https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.4.1

**Comment by staltz** [comment]
It works, thanks :)
