### ISSUE TITLE
[react-native] Android app crashes when starting node

### ISSUE THREAD

**Issue by stoically** [janeasystems/nodejs-mobile#192]
Today I was starting to get random build errors (without any details) when running `react-native run-android` - I guess *something* changed on my system. I've updated the Android SDK and NDK, which made the build work again - but now the app just crashes (on a device and in the avd emulator with API Level 28) after the call to `nodejs.start('main.js');` without any error to be seen in `react-native log-android`.

Also tried with a fresh `react-native init test` project and just nodejs-mobile-react-native installed, but same issue.

```
Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b16-5323222 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic
Ubuntu 18.04.2 LTS

Android SDK Build-Tools 29-rc3
Android Emulator 29.0.9
Android SDK Platform-Tools 28.0.3
Android SDK Tools 26.1.1

cat ndk-bundle/source.properties 
Pkg.Desc = Android NDK
Pkg.Revision = 19.2.5345600

adb --version
Android Debug Bridge version 1.0.41
Version 28.0.3-5475833
```

Not sure how to debug this further - please let me know if I can provide more information.

**Comment by stoically** [comment]
Welp, I've simply forgot to `npm install` in `nodejs-assets/nodejs-project` - and so `require`ing of a not-existent module crashed the app.

**Comment by vedant-dobby** [comment]
I am trying to import the azure-iot-device module. 
As soon is I try to import it the application crashes. I have tried to create a seperate node folder or adding the dependencies in package.json.
Any help would be much appreciated!!

**Comment by stoically** [comment]
@vedant-dobby Try to check `adb logcat` for a specific error.

**Comment by vedant-dobby** [comment]
@stoically
I did adb logcat and this is the error log before app crashes:

08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE: 
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE: Error: Cannot find module 'azure-iot-device-mqtt'
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Module.require (internal/modules/cjs/loader.js:636:17)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at require (internal/modules/cjs/helpers.js:20:18)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at cloudCall (/data/data/com.dobbyautomations/files/nodejs-project/main.js:11:16)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Object.<anonymous> (/data/data/com.dobbyautomations/files/nodejs-project/main.js:58:1)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Module._compile (internal/modules/cjs/loader.js:688:30)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at Module.load (internal/modules/cjs/loader.js:598:32)
08-21 12:47:28.953 31091 31170 E NODEJS-MOBILE:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

I don't know how to resolve this. I have install the respective modules. It's not working

**Comment by stoically** [comment]
Does the directory `nodejs-assets/nodejs-project/node_modules/azure-iot-device-mqtt` exist?

**Comment by vedant-dobby** [comment]
Hi @stoically 

This is what I got when I did npm install azure-iot-device-mqtt and ran the application again.

```
08-21 12:19:28.032 27467 27521 E AndroidRuntime: FATAL EXCEPTION: Thread-3
08-21 12:19:28.032 27467 27521 E AndroidRuntime: Process: com.dobbyautomations, PID: 27467
08-21 12:19:28.032 27467 27521 E AndroidRuntime: java.lang.RuntimeException: Node assets copy failed
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:106)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/type/test/_lib/class-if-supported.js
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:755)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:732)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:431)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:371)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:30)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:103)
08-21 12:19:28.032 27467 27521 E AndroidRuntime: 	... 1 more
08-21 13:26:36.052  3619  3686 E AndroidRuntime: FATAL EXCEPTION: Thread-3
08-21 13:26:36.052  3619  3686 E AndroidRuntime: Process: com.dobbyautomations, PID: 3619
08-21 13:26:36.052  3619  3686 E AndroidRuntime: java.lang.RuntimeException: Node assets copy failed
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:106)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/type/test/_lib/class-if-supported.js
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:755)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:732)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyAsset(RNNodeJsMobileModule.java:431)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.copyNodeJsAssets(RNNodeJsMobileModule.java:371)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule.access$100(RNNodeJsMobileModule.java:30)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:103)
08-21 13:26:36.052  3619  3686 E AndroidRuntime: 	... 1 more
08-21 13:26:36.058  3619  3711 D OSTracker: OS Event: crash

```

**Comment by stoically** [comment]
It complains that `nodejs-project/node_modules/type/test/_lib/class-if-supported.js` doesn't exist - might need to install the `type` package as well. If that doesn't help or it already is installed, then it might be that `nodejs-mobile` has a problem with the `type` package for some reason - in that case I can't help and you might want to open a new issue about it.

**Comment by jaimecbernardo** [comment]
@vedant-dobby opened a new issue here: https://github.com/JaneaSystems/nodejs-mobile/issues/223
