### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by scriptjs** [janeasystems/nodejs-mobile#2]
Hello I am hoping you can establish a gitter channel for communication. Thank you.

**Comment by orangemocha** [comment]
Hi @scriptjs . Thanks for your suggestion. 

Did you see that we have a [mailing list](https://groups.google.com/group/nodejs-mobile) ?

I really gitter myself. My thinking though is that at this early stage, a Giitter room is going to be a bit lonely. When we have a larger community and a few regulars, having a chat room will make more sense.

**Comment by scriptjs** [comment]
The community is building quickly, it would be great to capture a log of conversation from inception of the release of the project than to wait for a larger volume of people. Worse case one might have to wait for a response which is fine I think.

**Comment by orangemocha** [comment]
@scriptjs having some technical issues with Gitter, but I am working on it.

**Comment by scriptjs** [comment]
sweet! Thank you.

**Comment by orangemocha** [comment]
Sorry for the delay. I finally managed to create a channel on gitter: https://gitter.im/nodejs-mobile/community

I am also adding it to the README with https://github.com/janeasystems/nodejs-mobile/pull/14.

**Comment by orangemocha** [comment]
Fixed. Also updated the README and the website.
