### ISSUE TITLE
Getting Error after react-native link nodejs-mobile-react-native

### ISSUE THREAD

**Issue by s0ld13r** [janeasystems/nodejs-mobile#202]
After
npm install nodejs-mobile-react-native --save
react-native link nodejs-mobile-react-native
I get an error when trying to run Sync Project With Gradle Files

ERROR: File '/home/sergey/my-projects/points-of-light/AwesomeProject/android/build/nodejs-assets' specified for property '$1' is not a file.

and 
when i am run:  react-native run-android
A problem was found with the configuration of task ':nodejs-mobile-react-native:GenerateNodeProjectAssetsLists'.
> File '/home/sergey/my-projects/points-of-light/AwesomeProject/android/build/nodejs-assets' specified for property '$1' is not a file.

**Comment by jaimecbernardo** [comment]
Hi @s0ld13r ,
Thank you for opening the issue. I've been able to replicate it.
Newer versions of Gradle used by react-native deprecated the use of `inputs.file` and `outputs.file` when referring to directories.
A fix for this was released in https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.4.3
Please give it a try.

**Comment by s0ld13r** [comment]
Thanks a lot. Everything works fine
