### ISSUE TITLE
How to check if instance is running ?

### ISSUE THREAD

**Issue by mfachmirizal** [janeasystems/nodejs-mobile#203]
Hello...
how can we know if node js mobile is running ?
my platform is react-native
Thankyou..

**Comment by jaimecbernardo** [comment]
Hi @mfachmirizal ,
Not sure about the specifics of your needs, but sending a message from node that you'd look check to see if it started would be a way to do it, or sending a query through the bridge and checking for a response.
Other than that, there's no direct API right now.

**Comment by mfachmirizal** [comment]
so there's no direct API for right now.. okay thanks..
