### ISSUE TITLE
cordova plug-in update to latest nodejs mobile v0.1.3

### ISSUE THREAD

**Issue by ksplache** [janeasystems/nodejs-mobile#21]
Are there plans to update the Node.js mobile cordova plug-in to the latest v0.1.3 release?  Or are there instructions on how to update it to the latest release?  I'd be willing to give it a try with some brief instructions.

**Comment by bil-ash** [comment]
Yeah,this is desired

**Comment by jaimecbernardo** [comment]
The `nodejs-mobile-cordova` `v0.1.2` has been published to npm. It updates the `nodejs-mobile` core library to `v0.1.3`. The complete Changelog is [here.](https://github.com/janeasystems/nodejs-mobile-cordova/blob/unstable/CHANGELOG.md)

I'm closing this issue accordingly. Thank you.
