### ISSUE TITLE
Get "bad ELF magic" error when require sqlite3

### ISSUE THREAD

**Issue by scottxu64** [janeasystems/nodejs-mobile#215]
Project: nodejs-mobile
Version: 0.2.1
Mobile device: Samsung S9
Mobile OS and version: Android P
Development Node.js: v10.15.3
Development platform: 64-bit (Windows)

I have an error when I try to require sqlite3 from node code, JS code like this:
	var sqlite3 = require('sqlite3').verbose();
	var db = new sqlite3.Database('./myDb.db');		// myDb.db is copied to node project folder. This node code works fine in Windows
	
error message like this:
	Error: dlopen failed: "/data/data/com.example.myapplication/files/nodejs-project/node_modules/sqlite3/lib/binding/node-v64-android-arm64/node_sqlite3.node" has bad ELF magic

In the beginning, logcat indicated it can't find node-v64-android-arm64/node_sqlite3.node, which is because I ran "npm i" from windows. I generated node_sqlite3.node for arm64-v8a using node-pre-gyp. The generated file is in "node-v64-android-arm64-v8a" folder, so I manually renamed it to "node-v64-android-arm64".
Some posts mentioned it is because different versions of NDK were used. I used a Mac to build those .node files from pre-gyp files. Only used python and Xcode as in node-sqlite3 home page described. Not sure if it is the issue.

 Didn't find too many posts about this ELF magic topic, maybe I am using a wrong key word. Any hint, guidance would be much appreciated.
By the way, thank you for your great work, other than this issue, everything I needed works great!

**Comment by scottxu64** [comment]
2019-07-19 08:54:09.774 12461-12567/com.example.myapplication E/NODEJS-MOBILE: internal/modules/cjs/loader.js:717
      return process.dlopen(module, path.toNamespacedPath(filename));
                     ^
    
    Error: dlopen failed: "/data/data/com.example.myapplication/files/nodejs-project/node_modules/sqlite3/lib/binding/node-v64-android-arm64/node_sqlite3.node" has bad ELF magic
        at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
        at Module.load (internal/modules/cjs/loader.js:598:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
        at Function.Module._load (internal/modules/cjs/loader.js:529:3)
        at Module.require (internal/modules/cjs/loader.js:636:17)
        at require (internal/modules/cjs/helpers.js:20:18)
        at Object.<anonymous> (/data/data/com.example.myapplication/files/nodejs-project/node_modules/sqlite3/lib/sqlite3.js:4:15)
        at Module._compile (internal/modules/cjs/loader.js:688:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
        at Module.load (internal/modules/cjs/loader.js:598:32)

**Comment by scottxu64** [comment]
so I noticed all the .node files are the same size, they actually are the same files regardless the "--target_platform=android --target_arch=arm64" parameters provided. They work in the host environment, like file generated in MacOS works for MacOS, Linux works for Linux.
No errors thrown, just like those parameters are override by host settings. Generated folder names match parameters though, that fooled me earlier. 

This is the code I used to build .node files:
npm install sqlite3 --target_platform=android --target_arch=arm64 --target=10.15.3 --build-from-source

**Comment by jaimecbernardo** [comment]
Hi @scottxu64 ,

Thank you for the feedback.

sqlite3 is a native module which needs to be built for the target libray / architecture, as you've figured out.

Currently, the plugins are using `nodejs-mobile-gyp` as a way to build it for mobile and using nodejs-mobile headers. After some setup in gradle, this is how they end up being built:
https://github.com/JaneaSystems/nodejs-mobile-cordova/blob/823fe002e8312e3abba76f9b8aa358a490f76eac/src/android/build.gradle#L215-L251

We have some samples with sqlite3 using the plugins, so this is a question of building the module with your environment and using it at runtime:
- https://github.com/JaneaSystems/nodejs-mobile-samples/tree/master/cordova/UseNativeModules
- https://github.com/JaneaSystems/nodejs-mobile-samples/tree/master/react-native/UseNativeModules

I hope this is helpful.

**Comment by zt64** [comment]
I've been trying to make a discord bot using SQLite and got this exact same error.  Wierd to find that this is on the exact same phone and same OS.  Anyway here's my error in case there's some difference.

internal/modules/cjs/loader.js:815
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

```
Error: dlopen failed: "/storage/emulated/0/Minkinator/node_modules/better-sqlite3/build/better_sqlite3.node" has bad ELF magic
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/storage/emulated/0/Minkinator/node_modules/better-sqlite3/lib/database.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
```

**Comment by scottxu64** [comment]
Hey @jaimecbernardo , really appreciate your response. I ended up with mocking your react-native project gradle files and successfully generated the node addon file I need.

And @Litleck , thank you for supporting this discussion, but it is not about the phone and os or even nodejs-mobile. The simple node-pre-gyp, node-gyp approaches doesn't use all passed in arguments at this moment. Exporting environment variables doesn't work neither, or I missed something.
You may need to adapt 3 gradle tasks to your project: CopyNodeProjectAsset, MakeToolchain,BuildNpmModules, and provide required arguments. It is not hard, but really a lot to read and find. The immediate take away is that nodejs-mobile and node addons and a db file can work together within Android. That was my biggest concern. And you can temporarily test your code using my generated file at: https://github.com/scottxu64/node-v64-android-arm64 . You should generate you own later for security concerns.

**Comment by sallespro** [comment]
@scottxu64 would you recall how the "mocking" fixed this ? 

i am stuck at `Error: dlopen failed: "/data/data/com.test1/files/nodejs-project/node_modules/sqlite3/lib/binding/napi-v3-platform-arch/node_sqlite3.node" has bad ELF magic: cffaedfe`

**Comment by lmarcelocc** [comment]
@sallespro , did you got any solution for your issue? I'm getting exactly the same.

**Comment by lmarcelocc** [comment]
@jaimecbernardo can you help ? Thanks

**Comment by sallespro** [comment]
Hi, I didn't do through this compilation setups any longer, but maybe this
helps with nodejs-mobile. https://blog.mauve.moe/posts/hyper-react-native

Em qua, 15 de dez de 2021 11:30, lmarcelocc ***@***.***>
escreveu:

**Comment by paulordyl** [comment]
@jaimecbernardo how i can contact you? need help
