### ISSUE TITLE
Please add Cocoapods support

### ISSUE THREAD

**Issue by sampatel037** [janeasystems/nodejs-mobile#218]
* **Project**:
* **Version**:
* **Mobile device**:
* **Mobile OS and version**:
* **Development Node.js**:
* **Development platform**:

**Comment by jaimecbernardo** [comment]
Hi @sampatel037 ,
There's been a recent PR to add a podspec to the library: https://github.com/JaneaSystems/nodejs-mobile/commit/2a0a302aa614ff966176f412756836b68e020ce2

Are you having some issues with it?

**Comment by sampatel037** [comment]
Tried that too, for some reason pod installation is stuck at pre-downloading `NodeMobile`.
I have also tried @jgtoriginal 's solution from https://github.com/jgtoriginal/RNNodeJsMobile which results in rctbridgemodule.h file not found and _napi_call_function error.

So I have decided to go back to RN v0.59.9

**Comment by jaimecbernardo** [comment]
Thank you @sampatel037 , podspec support needs to be added to support v0.60+ 
It's related to this issue: https://github.com/JaneaSystems/nodejs-mobile/issues/216

**Comment by jaimecbernardo** [comment]
We've just released [v0.5.0](https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.5.0) to fix v0.60.x support, adopting the new autolink features of `react-native`, which include a podspec. Please give it a try.

**Comment by sampatel037** [comment]
Thank You very much
