### ISSUE TITLE
cordova plugin nodejs api strict mode syntax error

### ISSUE THREAD

**Issue by stoically** [janeasystems/nodejs-mobile#22]
* **Version**:
nodejs-mobile-cordova: 0.1.2
cordova: 7.1.0
* **Platform**:
Host: Linux pc 4.4.0-98-generic 121-Ubuntu SMP x86_64 GNU/Linux
Device: Genymotion Custom Phone (x86), Android 6.0.0, API23, WebView version 44.2403.119

Hi,

thanks for your awesome work on nodejs-mobile!

I noticed when adding the cordova plugin to an android platform, building it and running it on a device, the console logs the following error messages:

```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode plugins/nodejs-mobile-cordova/www/nodejs_apis.js:5
Uncaught Error: Module nodejs-mobile-cordova.nodejs does not exist. cordova.js:1470
```

To solve this it's necessary to put `www/nodejs_apis.js` into strict mode. With [this change](https://github.com/janeasystems/nodejs-mobile-cordova/pull/2/commits/d98c4f0e7455630589e8dbb0f61893d493e6a499) the plugin loads and logs the welcome message as expected.

```
NodeJs Engine Started
[cordova] received: Replying to this message: Hello from Cordova! index.js:32
```

Maybe I'm missing something and the change isn't necessary at all - in this case please let me know. If not I hope this helps.

Best regards

**Comment by enricogior** [comment]
Hi @stoically 
thank you for opening the issue.
I'm not sure why you got the error, we tested it on latest Android 8.0.0 on Nexus 6P and it didn't happen, it may be something happening only on previous Android versions.
But given your fix works fine, we will merge your PR.
Thanks!
