### ISSUE TITLE
Callback not working?

### ISSUE THREAD

**Issue by vedant-dobby** [janeasystems/nodejs-mobile#220]
* **Project**:Dobby Automations
* **Version**: React Native version 0.59.9
* **Mobile device**: OnePlus 5
* **Mobile OS and version**: Android 9
* **Development Node.js**: node version 12.6.0
* **Development platform**:  ubuntu 18.04.2 LTS

I am trying to run call backs in nodejs-mobile. The application is crashing.

I have posted the code below:

```
 var rn_bridge = require('rn-bridge');
// Echo every message received from react-native.

function apiCall (callback) {
var Protocol = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').Client;
var Message = require('azure-iot-device').Message;
var iotData = ''

var connectionString = 'can't reveal the access key';

var client = Client.fromConnectionString(connectionString, Protocol);

var connectCallback = function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    // console.log('Client connected');
    client.on('message', function (msg) {

      iotData = msg.data.toString('utf8')
      callback(iotData)
    })

      var date = new Date();
      var timestamp = date.getTime();
      var data = JSON.stringify({"data":{"Status":1}, "toDevice":"iot-cbf434d6", "fromDevice":"vedantPhone",'timestamp':timestamp});
      var message = new Message(data);
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message);


    client.on('error', function (err) {
      console.error(err.message);
    });

    client.on('disconnect', function () {
      client.removeAllListeners();
    });
  }
}
function test (callback) {
  callback('Call back is fine')
}

client.open(connectCallback);
// return iotData
}

rn_bridge.channel.on('message', (messageData) => {

})

apiCall(data => {
   rn_bridge.channel.send(data)
})
```

Anybody help please. I'm not able to discern any pattern here.

@jaimecbernardo

**Comment by jaimecbernardo** [comment]
Hi @vedant-dobby ,
Checking the reason for the crash in `adb logcat` would be the first step to try and understand what might be the issue. Do you get any errors there?

**Comment by vedant-dobby** [comment]
Okay let me try that

**Comment by vedant-dobby** [comment]
@jaimecbernardo I'm sorry I'm not able to understand but there doesn't seem any errors

**Comment by vedant-dobby** [comment]
Is there something wrong with my code?

**Comment by vedant-dobby** [comment]
@jaimecbernardo 
Hi I think I've isolated the problem. I am not able to run any program where I am importing some package e.g. 
var Protocol = require('azure-iot-device-mqtt').Mqtt;
etc.

Where do I need to install these packages ? Or can you tell me what am I doing wrong.

**Comment by vedant-dobby** [comment]
Hi @jaimecbernardo 
I tried to write a different package.json for the node project and followed the steps in trouble shooting sectionof Readme. 
When I add my dependencies in package.json, and run npm install, all the dependencies get installed. But the app is crashing. When I delete node_modules folder created due to npm install it runs again. How to solve this?

**Comment by jaimecbernardo** [comment]
Hi @vedant-dobby,

Closing this issue in favor of the more detailed issue you've opened with the logcat output: https://github.com/JaneaSystems/nodejs-mobile/issues/223
