### ISSUE TITLE
How to shut down node gracefully

### ISSUE THREAD

**Issue by scottxu64** [janeasystems/nodejs-mobile#221]
Project: nodejs-mobile
Version: 0.2.1
Mobile device: Samsung S9
Mobile OS and version: Android P
Development Node.js: v10.15.3
Development platform: 64-bit (Windows)

I noticed after I exit my Android app, node instance still works. I called interrupt() to kill the thread running node instance. It kills the thread but node instance is still alive.

I tried node process.exit() method as mentioned in this post: #https://github.com/JaneaSystems/nodejs-mobile/issues/19  It crushes entire android app immediately, without exceptions. I also tried to wrap startNodeWithArguments() with try catch, but obviously it doesn't stop the crushing. The C/C++ part discussing is quite foreign to me. I'll dive in if I have to.

I tried to use a npm package called 'http-shutdown' to gracefully shut down node, it partially close node as no communication can be established, and Android app doesn't crush. But the next time I start node, I got this not very informative error, same as trying to run multiple node instances:
```
2019-08-11 19:55:54.411 14103-15551/com.example.myapplication E/NODEJS-MOBILE: #
    # Fatal error in , line 0
    # Check failed: !platform_.
    #
    #
    #
    #FailureMessage Object: 0x6f7bdfdf10
```

My current solution is shut down everything else normally then let node crush Android application. It looks the same to users but it is not a solution.
I think terminating node instance gracefully would be a quite common practice when using nodejs-mobile. Any guidance of best practice or an API that I missed or work around would be much appreciated.

**Comment by jaimecbernardo** [comment]
Hi @scottxu64

`startNodeWithArguments` is supposed to return once the libuv loop is not waiting on anything.
You might still have some handles open or listeners registered.
Does this happen if all the node code does is calling a `console.log('Hello');`, for example?
Hope this is helpful.

**Comment by scottxu64** [comment]
Hey @jaimecbernardo 
Thank you for your response, I just tried your suggestion to simplify main.js to` console.log('Hello');`, then start startNodeWithArguments() via a service. Logcat has the "Hello" printed out. Then I stop the service, then run startNodeWithArguments() via service again, got same error:
```
2019-08-12 20:46:48.092 29775-30528/com.example.myapplication I/NODEJS-MOBILE: Hello
2019-08-12 20:46:55.247 29775-29775/com.example.myapplication D/ViewRootImpl@51cef1d[MainActivity]: ViewPostIme pointer 0
2019-08-12 20:46:55.329 29775-29775/com.example.myapplication D/ViewRootImpl@51cef1d[MainActivity]: ViewPostIme pointer 1
2019-08-12 20:46:58.669 29775-29775/com.example.myapplication D/ViewRootImpl@51cef1d[MainActivity]: ViewPostIme pointer 0
2019-08-12 20:46:58.743 29775-29775/com.example.myapplication D/ViewRootImpl@51cef1d[MainActivity]: ViewPostIme pointer 1
2019-08-12 20:46:58.777 29775-30803/com.example.myapplication E/NODEJS-MOBILE: #
    # Fatal error in , line 0
    # Check failed: !platform_.
    #
    #
    #
    #FailureMessage Object: 0x6f7c38df10
```
I've separated loadLibrary logic and node file handling logic to other parts, leave start node logic in a foreground service, but that's all on the Android side, not sure if they have anything to do with this issue. Here is part of my foreground service code:
 ```
private Thread nodeThread;

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        final String nodeDir = getApplicationContext().getFilesDir().getAbsolutePath() + "/nodejs-project";
        if (intent != null) {
            // foreground service
            final Intent notificationIntent = new Intent(this, MainActivity.class);
            PendingIntent pendingIntent = PendingIntent.getActivity(
                    this, 0, notificationIntent, 0);

            Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                    .setContentTitle("Node service is running")
                    .setContentText("hello world")
                    .setSmallIcon(R.drawable.ic_home)
                    .setContentIntent(pendingIntent)
                    .build();

            startForeground(1, notification);

            // node service
            if (nodeThread == null) { //We just want one instance of node running in the background.
                nodeThread = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        startNodeWithArguments(new String[]{"node", nodeDir + "/main.js"});
                    }
                });

                nodeThread.start();
            }

        }
        return START_NOT_STICKY;
    }

    @Override
    public void onDestroy() {
        if (nodeThread != null) {
            nodeThread.interrupt();
            nodeThread = null;
        }
        super.onDestroy();
    }
```
I think start stop app on a mobile device is a very common use case, there might be some patterns or solutions already? Could your help with maybe some sample code from previous success stories using nodejs-mobile, if it is not too much trouble. 
Once again really appreciate your great work. Node instance works smoothly on phones old as Moto G to new as Samsung S9. It is just the shutting down issue needs to be ironed out for me now.

**Comment by jaimecbernardo** [comment]
Hi @scottxu64 ,

The service is likely being run in the same process through its various iterations.
You're running into the assert in v8 that checks if there's a V8 already started in the process: https://github.com/JaneaSystems/nodejs-mobile/blob/5513cc885562983d8ed5c042e99e17948c3fa0d2/deps/v8/src/v8.cc#L92-L98

In many places, node assumes it will be the only instance running in the same process through its lifetime, which makes it being started twice in the same process error-prone. The workaround would probably be to keep the node instance running and have it respond to different calls to it without starting a new instance.

For more discussion on this topic, this has also been discussed in other issues, like:
https://github.com/janeasystems/nodejs-mobile/issues/66
https://github.com/janeasystems/nodejs-mobile/issues/98
https://github.com/janeasystems/nodejs-mobile/issues/166

I hope this is helpful.

**Comment by scottxu64** [comment]
Hi @jaimecbernardo ,
Just want to let you know as a result I used android's System.exit(0) method to kill node thread. And this looks fine to Google Play, as of Oct. 2019. I know this because my app passed "pending publish" a few days ago.
No words can express my gratitude to your great code, documentation and kindly replies.

Hope this can help other people struggling like I was. If you want to see for yourself, search "HVAC Sentry" in google play. I'll also be happy to answer your tech/non-tech questions.
