### ISSUE TITLE
Null Is Not An Object (Evaluating RNNodeJsMobile.startNodeProject)

### ISSUE THREAD

**Issue by theoparis** [janeasystems/nodejs-mobile#225]
* **Project**: 
* **Version**:
* **Mobile device**: iphone 6s
* **Mobile OS and version**: ios 13
* **Development Node.js**: 
* **Development platform**: mac os mojave

In my react native component, i added `nodejs.start("main.js")` inside componentWillMount
when i launched the app it gave me an error saying

TypeError: null is not an object (evaluating 'RNNodeJsMobile.startNodeProject')
This error is located at:
Home (at sceneview.js:9)
Scemeview at stackview layout.tsx
...
I don't know what the issue is...
I simply added the necessary code to use react native nodejs mobile and it just gave me that error.
I am using createAppContainer along with createStackNavigator from react-navigation
and the component is a class extending component  
I have the main.js file and the required nodejs-project and assets folders.

**Comment by jaimecbernardo** [comment]
Hi @creepinson ,

It's possible that you didn't link the project. There's also an issue right now where react-native 0.60+ won't link successfully.

Try a sample to see if the setup could be the issue:
https://github.com/JaneaSystems/nodejs-mobile-samples/tree/master/react-native/UseMultipleChannels

If this is not helpful, version information about the react-native version you are using or a sample repo would be useful.

**Comment by n3oney** [comment]
Hey @jaimecbernardo! I am having the same issue, being on react native 0.57.3, it won't link correctly. Any help?

Edit: to clarify, i think the newest @react-native-community/cli doesn't work with this module well. I downgraded it to 2.0.0 and it seems to be linking correctly. I just re-linked the whole module and re-build the app in Xcode and... `TypeError: null is not an object (evaluating 'RNNodeJsMobile.startNodeProject')`

**Comment by theoparis** [comment]
Sorry for not responding, I've been working on other projects and I forgot about this issue. I'll try to open a similar (or the same) react native project and see if it still happens.

**Comment by jaimecbernardo** [comment]
We've just released [v0.5.0](https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.5.0) to fix v0.60.x support, adopting the new autolink features of `react-native`, meaning the react-native-community/cli is no longer used by the postlink hook. It might fix this issue.

**Comment by n3oney** [comment]
Okay, I will check it out.

**Comment by n3oney** [comment]
I made a new project with `react-native` 0.60.5 and `nodejs-mobile-react-native` v0.5.0
As there's an autolink now, I didn't `react-native link nodejs-mobile-react-native`. Then, i `react-native run-ios`. And... `TypeError: null is not an object (evaluating 'RNNodeJsMobile.startNodeProject')`
I'm losing hope... think might need to run an API in Node to use something like that... seems not very good though.

**Comment by jaimecbernardo** [comment]
Did you try the `pod install` instructions for the autolinking?

https://github.com/react-native-community/cli/blob/85198d211588f4b1472f282c8c823b32e3ddbc26/docs/autolinking.md#autolinking

https://github.com/JaneaSystems/nodejs-mobile-react-native/tree/cf4c90984e010176f85e76c7931ca8e58e229e57#installation

**Comment by n3oney** [comment]
Ah, silly me. Of course I didn't. I will rebuild the app and then edit this reply.

Edit: Amazing! Seen an alert: "From node: node was initialized"

**Comment by n3oney** [comment]
Tips for people here in the future: use 0.5.0, don't `react-native link` the module, if you are using iOS, remember to `cd ios && pod install && cd ..` and these should be all the steps required to make the module work
I think this can be closed now @jaimecbernardo and thanks for the help!

**Comment by jaimecbernardo** [comment]
Thank you for the feedback :+1:

**Comment by JosipSylo** [comment]
It would be useful to update https://code.janeasystems.com/nodejs-mobile/getting-started-react-native#installing-the-plugin explaining the skipping of  `react-native link`.

**Comment by acerbastimur** [comment]
I got this error on Android, anybody to help ?

**Comment by chebyte** [comment]
still no working for ios, I'm using last versions of react-native and nodejs-mobile and I ran pod install insde ios folder but i still getting this error

**Comment by chebyte** [comment]
why is close this issue? still is not working
