### ISSUE TITLE
Possible to enable JIT on jailbroken iOS?

### ISSUE THREAD

**Issue by stanica** [janeasystems/nodejs-mobile#226]
If so, how?

**Comment by jaimecbernardo** [comment]
Hi @stanica ,
The scenario you are asking about is not supported.
If trying to enable JIT, the first step would be by trying to build without the [`--without-chakra-jit` flag](https://github.com/JaneaSystems/nodejs-mobile/blob/d731966cf36550c68b4d7ce22765ca7fd73d0733/tools/ios_framework_prepare.sh#L20)
