### ISSUE TITLE
Linking errors while building for iOS Release mode

### ISSUE THREAD

**Issue by jlongster** [janeasystems/nodejs-mobile#231]
Project: nodejs-mobile-react-native
Version: 0.5.0
Mobile device: iPhone XR
Development Node.js: v10.13.0
Development platform: Darwin jlong-16428.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

I'm on react-native 0.61.2 and using a Podfile which can be seen [here](https://gist.github.com/jlongster/88d67f6b6a3a1fb46d69376ef0f17ae9)

I'm on macOS 10.15. This project has worked beautifully, but I can't get it to compile in Release mode. It compiles just fine in Debug mode, both for device and simulator.

I get these link errors:

<img width="292" alt="Screen Shot 2019-10-30 at 4 49 11 PM" src="https://user-images.githubusercontent.com/17031/67897869-9f8a7300-fb35-11e9-896f-d750f46e9e44.png">

Is there anything else I need to do to add these libraries?

**Comment by jlongster** [comment]
I figured this out. I had to up the deployment target to iOS 11 to make sure it's targeting arm64 only.

**Comment by export-mike** [comment]
@jlongster right I'm about to use nodejs-mobile for the first time and about to upgrade react native as well. so targeting ios 11 fixes the issue? i'm currently supporting ios9
