### ISSUE TITLE
Express Server not available on a Samsung Galaxy Tab A

### ISSUE THREAD

**Issue by bknill** [janeasystems/nodejs-mobile#234]
Project: nodejs-mobile-cordova
Version: 3.3.4
Mobile device: Samsung Galaxy Tab A
Mobile OS and version: Android 9 
Development Node.js: 12.2.0
Development platform: Linux owner-Aspire-VN7-791 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I have a Node Server setup via nodejs-mobile.  

This runs fine on my Samsung S10 phone, however on the Tablet the Node Server is not accessable from another device over the network. It is accessible fine locally. 

I assume this is some security settings on the tablet, but I can't find them. 

Has anyone seen this before?

**Comment by jaimecbernardo** [comment]
Looks like a device setting indeed, or some sort of Application setting not allowing access from the Internet. It sounds like out of the scope of this repo, so I'm closing the issue.

**Comment by tdurand** [comment]
@bknill have you been able to solve this ? I'm trying to access the nodejs-mobile app from another device on the local network but it doesn't work... not sure how to open a port on the android device / if possible...
