### ISSUE TITLE
Can't resolve DNS records

### ISSUE THREAD

**Issue by bushev** [janeasystems/nodejs-mobile#235]
* **Project**: nodejs-mobile-cordova
* **Version**: 0.3.4
* **Mobile device**: iPhone Pro max
* **Mobile OS and version**:  iOS 13.1
* **Development Node.js**:  v10.16.0
* **Development platform**: Darwin MBR.fios-router.home 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

**Expected**: Get a list of SRV records.
**Actual**: Got error (see logs).

Code:

```javascript
'use strict';

const dns = require('dns')

dns.resolveSrv('_mongodb._tcp.cluster0-u0nfn.mongodb.net', (err, data) => {
    if (err) throw err;

    console.log(data)
})

```

Logs:

```
2019-12-19 00:39:32.250716-0500 MongoApp[12304:3158127] 0:39:32:250: WARNING: Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0-u0nfn.mongodb.net

warning()@../../src/providers/logger.ts:98:38
handleError()@../../src/providers/MongoDB.ts:2324:28
console.error()@../../src/providers/MongoDB.ts:284:41
_.find()@../../src/providers/MongoDB.ts:231:44
emitOne()@ionic://localhost/plugins/nodejs-mobile-cordova/www/nodejs_events.js:116:17
emit()@ionic://localhost/plugins/nodejs-mobile-cordova/www/nodejs_events.js:211:14
processData()@ionic://localhost/plugins/nodejs-mobile-cordova/www/nodejs_apis.js:84:19
allChannelsListener()@ionic://localhost/plugins/nodejs-mobile-cordova/www/nodejs_apis.js:99:38
callbackFromNative()@ionic://localhost/cordova.js:288:63
{anonymous}()@ionic://localhost/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js:129:35
{anonymous}()@ionic://localhost/build/plf:3:10149
{anonymous}()@ionic://localhost/build/plf:3:20245
{anonymous}()@ionic://localhost/build/plf:3:10844
o()@ionic://localhost/build/plf:3:7901
promiseReactionJob()@[native code]
```

Note: it works well in Simulator, but always fails on a device.

**Comment by jaimecbernardo** [comment]
Hi @bushev ,
Trying this on a device, it seems that `dns.getServers` is returning `127.0.0.1` as the only DNS server.
Adding some other DNS servers like `1.1.1.1` or `8.8.8.8` through `dns.setServers` seems to have fixed the issue for me.

**Comment by bushev** [comment]
I rediscovered this thread after three years. Somehow, I missed the GitHub notification. You've really made my day! Everything finally works!!! 🎊
