### ISSUE TITLE
Crash when a 3rd party node_module used

### ISSUE THREAD

**Issue by nomoreboredom** [janeasystems/nodejs-mobile#24]
* **Version**: v8.9.0
* **Platform**: 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Subsystem**: scrypt

Hi Jaime again :)

On the main.js, I am trying to use an own node_module, and I require it as:
```const wallet = require("xxx-lib/dist/src/services/wallet");```
When I try to run the app, I see the following error:
```
module.js:653
  return process.dlopen(module, path._makeLong(filename));
  ^

Error: dlopen(/Users/ardailgaz/Library/Developer/CoreSimulator/Devices/66D15641-52A4-4E1E-A848-D5455E7A1D40/data/Containers/Bundle/Application/FF6A6FB7-5207-4CA5-8AC9-D9BC81571F7F/USNApp.app/nodejs-project/node_modules/scrypt/build/Release/scrypt.node, 1): no suitable image found.  Did find:
	/Users/ardailgaz/Library/Developer/CoreSimulator/Devices/66D15641-52A4-4E1E-A848-D5455E7A1D40/data/Containers/Bundle/Application/FF6A6FB7-5207-4CA5-8AC9-D9BC81571F7F/USNApp.app/nodejs-project/node_modules/scrypt/build/Release/scrypt.node: mach-o, but not built for iOS simulator
   at Module._extensions[.node] (module.js:653:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/Users/ardailgaz/Library/Developer/CoreSimulator/Devices/66D15641-52A4-4E1E-A848-D5455E7A1D40/data/Containers/Bundle/Application/FF6A6FB7-5207-4CA5-8AC9-D9BC81571F7F/USNApp.app/nodejs-project/node_modules/scrypt/index.js:3:1)
   at Module.prototype._compile (module.js:624:5)
   at Module._extensions[.js] (module.js:635:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/Users/ardailgaz/Library/Developer/CoreSimulator/Devices/66D15641-52A4-4E1E-A848-D5455E7A1D40/data/Containers/Bundle/Application/FF6A6FB7-5207-4CA5-8AC9-D9BC81571F7F/USNApp.app/nodejs-project/node_modules/scrypt.js/node.js:1:63)
   at Module.prototype._compile (module.js:624:5)
```

Do you perhaps have any idea what may be causing this? This class uses web3 and some crypto functions, if it helps. Is there a way or some approach I have to follow when I use a node_module?

Thanks!

**Comment by lukaskollmer** [comment]
Node modules with native addons don't work on iOS since the native addon is compiled for the wrong architecture

**Comment by jaimecbernardo** [comment]
Hi @nomoreboredom ,
Thanks for the issue.

As @lukaskollmer mentioned, the native addons from npm don't work out of the box right now. Some discussion of this can be found on this issue: https://github.com/janeasystems/nodejs-mobile/issues/4

It might be possible to make the native modules work by including them directly on your project. The native bridge in the `nodejs-mobile-react-native` plugin works like a native module, but it is included in the Xcode project and registered as a `N-API` Native Plugin: https://github.com/janeasystems/nodejs-mobile-react-native/blob/bbf5c46566ab3b1789bfe633453f9d792f51f858/ios/rn-bridge.cpp#L260
The native part is then accessible in the node part like this: https://github.com/janeasystems/nodejs-mobile-react-native/blob/bbf5c46566ab3b1789bfe633453f9d792f51f858/install/resources/nodejs-modules/builtin_modules/rn-bridge/index.js#L3

So, in theory, the native plugins should be able to run by:
- Identifying the sources and adding them to your app's project so they are built and signed with it.
- Changing the register lines in the native code to register as native modules.
- Changing the require lines in the JS code to include the modules as if they were builtin modules.

I hope this was helpful.
If you end up trying to go this route for your project, please let us know the results.
I'd also like to invite you to join our gitter channel as it would be easier to answer some of the questions you might have in a more "chat-like" way by the community: https://gitter.im/nodejs-mobile/community

**Comment by sureshkumar-s89** [comment]
Hi, I'm beginner to cordova and this plugin. 

I have a node script from [this](https://itp.nyu.edu/physcomp/labs/labs-serial-communication/lab-serial-communication-with-node-js/) example which uses 'serialport' and 'ws' npm packages to communicate with weighing scale and host a WebSocketServer. It works in my windows machine and I want to run the same from my cordova application.

My requirement is to read/write data from/to weighing scale through rs232-to-usb/usb-otg serial connection from mobile application.

Is it possible to add 'serialport' and 'ws' npm packages into cordova application?
Is it possible to run the node script from cordova application with this nodejs-mobile plugin?

Sorry, if my understanding was wrong about this plugin.

**Comment by jaimecbernardo** [comment]
Hi, @sureshkumar-s89 ,
Thanks for your question.

Your understanding of the `nodejs-mobile-cordova` is correct, it would allow you to run node scripts from the cordova application.

However, it seems [the serialport package contains native code that needs to be compiled for the platform where the node code will run.](https://github.com/node-serialport/node-serialport/blob/master/binding.gyp)

Currently, `npm install` will compile this native code (`C++`) to the platform it is running in. It could work if you could compile the native code to the platform you are trying to run on (`iOS` / `Android`) in a way that could be loaded by `dlopen`.

Further discussion on trying to bring support for building native modules for `iOS` and `Android` in `nodejs-mobile` can be found in https://github.com/janeasystems/nodejs-mobile/issues/4 . This is currently unsupported, but is an issue we'd like to solve.

I hope this was helpful.

**Comment by sureshkumar-s89** [comment]
Hi, @jaimecbernardo 
Thank you so much for giving such clarity about the plugin and serialport package, it is really helpful.

While surfing internet, I come across the cordova plugin [`cordovarduino`](https://github.com/xseignard/cordovarduino) which I hope could satisfy my requirement.

Thanks again for your support.

**Comment by eggerand13** [comment]
@jaimecbernardo  Thank you for your great explanation. I do have a question though: How can I determine whether the modules I want to use are native modules or not?

I currently want to use: "request", "express" and "cheerio".
I don't know which one but one of them definitely freezes my app. 

Thank you for your help.

**Comment by jaimecbernardo** [comment]
Hi @eggerand13 , thank you for the question. We've been talking on the gitter channel, but I'll also leave the answer to the question here so more users can find it.

 One way to figure out if a module has native code is by checking the modules's folder for a `.gyp` file. It might be on one of those modules or on one of their dependencies.

**Comment by jaimecbernardo** [comment]
This issue is related to native modules support, so further discussion can be had in that issue:
https://github.com/janeasystems/nodejs-mobile/issues/4
