### ISSUE TITLE
Android project launch failed with nodejs-mobile-react-native

### ISSUE THREAD

**Issue by emclab** [janeasystems/nodejs-mobile#243]
* **Project**: nodejs-mobile-react-native
* **Version**: 0.5.0
* **Mobile device**: Android
* **Mobile OS and version**:Win10
* **Development Node.js**: 12.14.1
* **Development platform**:VS Code

PS C:\d\code\js\ipat_testmbrn> npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 875 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

> Task :nodejs-mobile-react-native:generateJsonModelDebug
debug|arm64-v8a :-- Check for working C compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
debug|arm64-v8a :-- Check for working C compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
debug|arm64-v8a :-- Detecting C compiler ABI info
debug|arm64-v8a :-- Detecting C compiler ABI info - done
debug|arm64-v8a :-- Detecting C compile features
debug|arm64-v8a :-- Detecting C compile features - done
debug|arm64-v8a :-- Check for working CXX compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
debug|arm64-v8a :-- Check for working CXX compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
debug|arm64-v8a :-- Detecting CXX compiler ABI info
debug|arm64-v8a :-- Detecting CXX compiler ABI info - done
debug|arm64-v8a :-- Detecting CXX compile features
debug|arm64-v8a :-- Detecting CXX compile features - done
debug|arm64-v8a :-- Configuring done
debug|arm64-v8a :-- Generating done
debug|arm64-v8a :-- Build files have been written to: C:/D/code/js/ipat_testmbrn/node_modules/nodejs-mobile-react-native/android/.externalNativeBuild/cmake/debug/arm64-v8a
debug|x86 :-- Check for working C compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
debug|x86 :-- Check for working C compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
debug|x86 :-- Detecting C compiler ABI info
debug|x86 :-- Detecting C compiler ABI info - done
debug|x86 :-- Detecting C compile features
debug|x86 :-- Detecting C compile features - done
debug|x86 :-- Check for working CXX compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
debug|x86 :-- Check for working CXX compiler: C:/Users/JunC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
debug|x86 :-- Detecting CXX compiler ABI info
debug|x86 :CMake Error: Unable to open check cache file for write. C:/D/code/js/ipat_testmbrn/node_modules/nodejs-mobile-react-native/android/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeTmp/CMakeFiles/cmake.check_cache
debug|x86 :CMake Error: Internal CMake error, TryCompile configure of cmake failed
debug|x86 :-- Detecting CXX compiler ABI info - failed
debug|x86 :-- Detecting CXX compile features
debug|x86 :CMake Error: Unable to open check cache file for write. C:/D/code/js/ipat_testmbrn/node_modules/nodejs-mobile-react-native/android/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeTmp/CMakeFiles/cmake.check_cache
debug|x86 :CMake Error: Internal CMake error, TryCompile configure of cmake failed
debug|x86 :-- Detecting CXX compile features - failed
debug|x86 :-- Configuring incomplete, errors occurred!
debug|x86 :See also "C:/D/code/js/ipat_testmbrn/node_modules/nodejs-mobile-react-native/android/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeOutput.log".
debug|x86 :See also "C:/D/code/js/ipat_testmbrn/node_modules/nodejs-mobile-react-native/android/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeError.log".

> Task :nodejs-mobile-react-native:generateJsonModelDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
41 actionable tasks: 2 executed, 39 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nodejs-mobile-react-native:generateJsonModelDebug'.
> Unable to delete directory 'C:\d\code\js\ipat_testmbrn\node_modules\nodejs-mobile-react-native\android\.externalNativeBuild\cmake\debug\x86_64\CMakeFiles\nodejs-mobile-react-native-native-lib.dir' after 10 attempts

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nodejs-mobile-react-native:generateJsonModelDebug'.
> Unable to delete directory 'C:\d\code\js\ipat_testmbrn\node_modules\nodejs-mobile-react-native\android\.externalNativeBuild\cmake\debug\x86_64\CMakeFiles\nodejs-mobile-react-native-native-lib.dir' after 10 attempts

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (C:\d\code\js\ipat_testmbrn\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\d\code\js\ipat_testmbrn\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at C:\d\code\js\ipat_testmbrn\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Command.handleAction (C:\d\code\js\ipat_testmbrn\node_modules\@react-native-community\cli\build\index.js:164:9)

**Comment by iankressin** [comment]
@emclab did you find the solution for this problem?
