### ISSUE TITLE
require.resolve(module_name) throws nothing even the module is not installed

### ISSUE THREAD

**Issue by emclab** [janeasystems/nodejs-mobile#245]
* **Project**:nodes-mobile-react-native, React Native 0.61.5
* **Version**:0.5.0
* **Mobile device**: iPhone simulator
* **Mobile OS and version**: iOS 13.3
* **Development Node.js**: 10.17.0
* **Development platform**: macOS Catalina

Used the following line in `main.js` under `/nodejs-assets/nodejs-project` to check if the module is installed

    rn_bridge.channel.send(require.resolve(module_name));

When module_name is `rn_bridge` and it did receive the message on RN side. However if I used a arbitrary module name which hasn't been installed, then there is nothing returned by `require.resolve()`. Just nothing, no error or what so ever.

**Comment by jaimecbernardo** [comment]
Hi @emclab ,

I've given this a try. When `module_name` is a module that doesn't exist, nodejs-mobile terminates with an error, as expected.
If you want to use a thrown error, you need to catch it in JavaScript.

```
try {
  require.resolve('doesnt-exist');
} catch (err) {
  rn_bridge.channel.send(err);
}
```
