### ISSUE TITLE
update on nodejs-mobile-react-native anytime soon?

### ISSUE THREAD

**Issue by emclab** [janeasystems/nodejs-mobile#246]
The current version of nodejs-mobile-react-native 0.5.0. The nodejs-mobile used is 0.2.1 and is behind the current stable of 0.2.2.  Going to have a upgrade with the nodejs-mobile-react-native soon?

**Comment by emclab** [comment]
I have a hard time to make ipfs 0.5.0 work with current release of nodejs-mobile-react-native.

**Comment by calm-rad** [comment]
I'm also interested in this question

**Comment by jaimecbernardo** [comment]
Hi, Sorry for the late response. We've just release `0.6.0` with nodejs-mobile `0.3.0`. We ended up skipping nodejs-mobile `0.2.0` for `nodejs-mobile-react-native`.
