### ISSUE TITLE
please add  license

### ISSUE THREAD

**Issue by adhavalboy** [janeasystems/nodejs-mobile#249]
* **Project**:
* **Version**:
* **Mobile device**:
* **Mobile OS and version**:
* **Development Node.js**:
* **Development platform**:

**Comment by orangemocha** [comment]
https://code.janeasystems.com/nodejs-mobile/license

**Comment by adhavalboy** [comment]
The year 2020 copyrights not updated :)

**Comment by jaimecbernardo** [comment]
Hi @adhavalboy ,
Could you please be more specific?

**Comment by adhavalboy** [comment]
resolved.
