### ISSUE TITLE
 Is it possible to upgrade to Node.JS v12 or higher?

### ISSUE THREAD

**Issue by jacobbubu** [janeasystems/nodejs-mobile#252]
* **Project**:
* **Version**:
* **Mobile device**:
* **Mobile OS and version**:
* **Development Node.js**:
* **Development platform**:

I found that node_mobile uses Node.JS v8.6.0. Is it possible to upgrade to Node.JS v12 or higher? If not, what is the reason?
Maybe this is a very basic question, but I have n’t found the answer in the history of the message.

**Comment by jaimecbernardo** [comment]
Hi @jacobbubu , Actually, nodejs-mobile has been using Node.js v10 for a while now, and it's recently been updated to NodeJs v12.
