### ISSUE TITLE
How can native oc code communicating with js code?

### ISSUE THREAD

**Issue by Txiaozhe** [janeasystems/nodejs-mobile#253]
* **Project**:
* **Version**:
* **Mobile device**:
* **Mobile OS and version**:
* **Development Node.js**:
* **Development platform**:

**Comment by jaimecbernardo** [comment]
Hi @Txiaozhe , Not sure what this is about. Could you please elaborate?

**Comment by Txiaozhe** [comment]
It is all right, thanks :)
