### ISSUE TITLE
Node loads slowly. Is there a `NodeLoaded` event? Or can I `await nodejs.start`? 

### ISSUE THREAD

**Issue by joshglenn** [janeasystems/nodejs-mobile#254]
* **Project**: nodejs-mobile-react-native
* **Version**:
* **Mobile device**: iOS Simulator, iPhone X
* **Mobile OS and version**: iOS 12.1
* **Development Node.js**: 
* **Development platform**:

Starting up node the first time takes some 8 seconds. So, during that time period, if the user takes actions in the UI that send messages to node, there is no response. Then suddenly, all those message come in at once. Is there an event which my app can listen to so I can avoid sending messages to node before it is ready to receive them? (I want to show a "loading" indicator or something of the sort during this 8 second period)

I am running this code in main.js (just the default example code)

```
var rn_bridge = require('rn-bridge');

// Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  // if(msg == 'beginJogUL') {
  //   rn_bridge.channel.send('dd'+msg);
  // }
  rn_bridge.channel.send(msg);
} );

// Inform react-native node is initialized.
rn_bridge.channel.send("Node was initialized.");
```

and in my React component:

```
  React.useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        //SplashScreen.preventAutoHide();

        // Load our initial navigation state
        //setInitialNavigationState(await getInitialState());

        /**
         * connect in to nodejs. See https://code.janeasystems.com/nodejs-mobile/getting-started-react-native
         * Note: useEffect is the functional equivalent for componentWillMount()
         */
        nodejs.start('main.js');
        nodejs.channel.addListener(
          'message',
          (msg) => {
            console.log('From node: ' + msg);
          },
          this 
        );
        
        // Load fonts
        await Font.loadAsync({
          ...Ionicons.font,
          'space-mono': require('./assets/fonts/SpaceMono-Regular.ttf'),
        });

        


      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e);
      } finally {
        setLoadingComplete(true);
        console.log('Ready to communicate with node');
        //SplashScreen.hide();
      }
    }

    loadResourcesAndDataAsync();
  }, []);
```

I'm not sure, but I think I might need to be able to "await" the nodejs.start command and/or the nodejs.channel.addListener , or listen for some "loaded" event.

Is there such a mechanism in nodejs-mobile?

**Comment by jaimecbernardo** [comment]
Hi @joshglenn ,
One way of achieving this would be to set a listener on your UI and wait for nodejs-mobile to send a message once it starts.

**Comment by joshglenn** [comment]
That sounds like the way to go. Thanks!
