### ISSUE TITLE
How to get node log on iOS native?

### ISSUE THREAD

**Issue by pantaopt** [janeasystems/nodejs-mobile#255]
I used nodejs-mobile framework in iOS.
I can see node log at xcode like terminal.

But i don't konw how to get these logs in iOS

Thanks.

**Comment by jaimecbernardo** [comment]
Hi @pantaopt ,
I'm not sure what you mean. The output gets shown in Xcode, like you mention.
If you want to get them elsewhere, you might need to redirect stdout through a pipe or something similar.

**Comment by pantaopt** [comment]
@jaimecbernardo 
Sorry for response you too later!
Thank you for your answer, i think your answer is right.
I have not been working in this work recently.
Thank you again. I will close this issue.
