### ISSUE TITLE
How to compile it to support arm64e(A12,A13)?

### ISSUE THREAD

**Issue by kvzn** [janeasystems/nodejs-mobile#263]
I tried adding below to line 970 of file `configure.py`, it compiled successfully with the target `arm64e` required project, but doesn't run.
```py
# for arm64e?
 o['variables']['arm_version'] = '8.3'
```
Anyone has idea?

**Comment by jaimecbernardo** [comment]
The `arm64` binaries are able to run on `arm64e` devices.
Haven't tried building it for `arm64e` directly. Why do you need this?

**Comment by kvzn** [comment]
> The `arm64` binaries are able to run on `arm64e` devices.
> Haven't tried building it for `arm64e` directly. Why do you need this?

Sorry, I thought it couldn't. Now it's OK, thanks a lot!
