### ISSUE TITLE
Setting up Express to work through Cordova on iOS

### ISSUE THREAD

**Issue by Ant-V** [janeasystems/nodejs-mobile#265]
* **Project**: nodejs-mobile-cordova
* **Version**: 0.4.1
* **Mobile device**: iPhone SE 2 (emulator) / iPhone X
* **Mobile OS and version**: iOS 13.4.1
* **Development Node.js**: v13.12.0
* **Development platform**: macOS 10.15.4

Hello, 
I'm trying to make express run from within node, but it doesn't seem to work.

My latest try was following the instructions from the [Cordova Getting Started Guide](https://code.janeasystems.com/nodejs-mobile/getting-started-cordova) and doing the following changes:

> /www/js/index.js

```
var app = {
  initialize: function () {
    document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
  },

  onDeviceReady: function () {
    this.receivedEvent('deviceready');
    startNodeProject();
  },

  receivedEvent: function (id) {
    var parentElement = document.getElementById(id);
    var listeningElement = parentElement.querySelector('.listening');
    var receivedElement = parentElement.querySelector('.received');

    listeningElement.setAttribute('style', 'display:none;');
    receivedElement.setAttribute('style', 'display:block;');

    console.log('Received Event: ' + id);
  }
};

app.initialize();

function startupCallback(err) {
  if (err) {
    console.log(err);
  } else {
    console.log('Node.js Mobile Engine started');
  }
};

function startNodeProject() {
  nodejs.start('main.js', startupCallback);
};

```
> /www/nodejs-projects/main.js
```
const express = require('express')
const app = express()
const port = 5000
app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

First of all I never see 'Example app listening [...]' at my output logs (I run it through Xcode to have an output of the Cordova logs)
Also, trying to access http://localhost:5000 returns  "cannot connect to the server", although I'm only running it from within index.html by adding <a> tags, which open in Safari, so maybe I'm also missing something on that front as well...

If anyone has any input it'd be greatly appreciated!

Thanks in advance

Edit: I toyed a bit around, cleaned everything, added it again and I can now run the app and have (until the app backgrounds itself) see "Hello World" on safari. So my question is, can I somehow have the Cordova WebView display the dynamically/express generated page?

**Comment by jaimecbernardo** [comment]
Hi,
Have you tried using `window.location='http://localhost:5000'` ?

**Comment by Ant-V** [comment]
Hello, 
yes, sadly it opens in Safari, in a new tab.

**Comment by jaimecbernardo** [comment]
Seemed to work for me, though.

This question is more like a general `Cordova` question, so you might have more luck through their general documentation and resources.

A simple search led me to this: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/index.html

**Comment by Ant-V** [comment]
This plugin seems to be able to do it, thanks!
