### ISSUE TITLE
Compiling 0.3.0 from scratch fails in F-Droid servers

### ISSUE THREAD

**Issue by staltz** [janeasystems/nodejs-mobile#266]
* **Project**: [Manyverse](https://github.com/staltz/manyverse) building nodejs-mobile as a dependency in F-Droid servers
* **Version**: nodejs-mobile 0.3.0
* **Mobile device**: (failed on compilation, so didn't run)
* **Mobile OS and version**: Android
* **Development Node.js**: host 12.16.0, same as target 
* **Development platform**: Linux (F-Droid build server)

See full details in this [F-Droid PR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6832). F-Droid has to compile all of its (open source) dependencies from scratch instead of taking prebuilt binaries. We already successfully compiled nodejs-mobile 0.2.1 in F-Droid servers using Android NDK r19c, but we did a simple update of nodejs-mobile to 0.3.0 and the NDK to r21b, but we got a compilation (apparently in linking phase) error. The full log is available at https://gitlab.com/fdroid/fdroiddata/uploads/0e604892df3e46abc012fa0a1dfe81ba/se.manyver_85.log.gz , but here is the tail end of the log: 

```
...
machine-operator.cc:(.text._ZN2v88internal8compilerlsERSoNS1_19StoreRepresentationE+0x36): undefined reference to `v8::internal::operator<<(std::ostream&, v8::internal::MachineRepresentation)'
collect2: error: ld returned 1 exit status
tools/v8_gypfiles/mksnapshot.host.mk:170: recipe for target '/home/vagrant/build/srclib/NodejsMobile/out/Release/mksnapshot' failed
make[1]: *** [/home/vagrant/build/srclib/NodejsMobile/out/Release/mksnapshot] Error 1
rm d5a8e9c0eeb93efae9d76d548eb0a1d96232fa1f.intermediate dc47bccbd7445c42bac5fc7e2d5e23f1667272c6.intermediate 2704a5066744c5e5db37bcfc0f0e00391dd51877.intermediate b480e6cbc9b73e3991eebff04fe9c4320ca56352.intermediate
Makefile:101: recipe for target 'node' failed
make: *** [node] Error 2
```

**Do you think updating to 0.3.1 would fix this?**

**Comment by jaimecbernardo** [comment]
Hi @staltz ,
`0.3.0` had a linking error when building for Android on Linux, due to the introduction of building snapshots.
`0.3.1` has fixes for this:
https://github.com/JaneaSystems/nodejs-mobile/commit/a3e9ae90d0f33ef9540ef40592b892f705d785d2
https://github.com/JaneaSystems/nodejs-mobile/commit/31f23350b946a25644f76804451be41b68c1a5bf

So, yes, I'd try 0.3.1 .
