### ISSUE TITLE
Reloading the project does not refresh main.js

### ISSUE THREAD

**Issue by HZSamir** [janeasystems/nodejs-mobile#27]
Hello again,
Refreshing the project with "Reload" or else "Live reload" and "Hot reloading" does not seem to have any effect on main.js, as new changes to the files are not taken into account.
For each modification I have to delete the app, stop the packager and run it again.

Is there some way to avoid this?
Thank you.

**Comment by jaimecbernardo** [comment]
Hi @Unforgiven-wanda ,
Thanks for the issue.

I'm assuming you are using the `nodejs-mobile-react-native plugin`. Hot reloading is not possible at the moment, as mentioned [in the plugin's `README.md`:](https://github.com/janeasystems/nodejs-mobile-react-native/blob/unstable/README.md#react-native-application)
> Attention: The Node.js project runs on a dedicated thread and as a singleton, so only the first nodejs.start() command will make any effect, as further calls will not start new threads. This means that if you use react-native's hotreload functionality you won't see any changes in the Node.js project.

Node.js assumes it has the whole process for itself, so the app will be restarted to restart the node part. Until there's a way to restart the Node.js runtime, I can't think of a way to avoid this.

I hope this was helpful.

**Comment by HZSamir** [comment]
Indeed it was. Thank you.

**Comment by weswes** [comment]
Do you mean that closing (from the app tray) and then re-launching the app must load changes done in main.js ?
It's seems that it's not working, I need to run react-native run-android every time I make a change in my nodejs file.

**Comment by jaimecbernardo** [comment]
Hi @weswes , You need to rebuild and reinstall the app, since the nodejs-project must be included in the APK's assets. `react-native run-android` is needed.
