### ISSUE TITLE
Background Tasks 

### ISSUE THREAD

**Issue by fangyuxi** [janeasystems/nodejs-mobile#270]
I started the Node.js service in an asynchronous thread. When the app is in the foreground, it can respond normally through the HTTP protocol. When the app is placed in the background and enters after a few minutes, this port cannot be accessed.

NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://127.0.0.1:3100/, NSErrorFailingURLKey=http://127.0.0.1:3100/, _kCFStreamErrorDomainKey=1}

**Comment by jaimecbernardo** [comment]
You didn't fill the header, but I'm supposing this is iOS.
Please read: https://github.com/JaneaSystems/nodejs-mobile/issues/62#issuecomment-380109120
