### ISSUE TITLE
Is it possible to debug the nodejs code?

### ISSUE THREAD

**Issue by tbiesemann** [janeasystems/nodejs-mobile#272]
Project: nodejs-mobile-react-native
Version: 0..6.0
Mobile device: Does not apply
Mobile OS and version: Android/iOS
Development Node.js: 12.16.1
Development platform: React-Native 0.62.2

I can see the logs in XCode, but is it also possible to debug the code?
Is this documented somewhere?

Thanks, Thomas

**Comment by jaimecbernardo** [comment]
This is a duplicate from https://github.com/JaneaSystems/nodejs-mobile/issues/5
Closing it.
Short answer: debugging depends on ICU, which is not included in the build currently.
