### ISSUE TITLE
how to implement reuse napi_env

### ISSUE THREAD

**Issue by lilulu2018** [janeasystems/nodejs-mobile#273]
* **Project**: **nodejs-mobile**
* **Version**: **0.1.3**
* **Mobile device**: **Xiaomi Mix2s**
* **Mobile OS and version**: **Android 9.0**
* **Development Node.js**: **10.16.0**
* **Development platform**: **Windows**

I was trying to communicate between js and android using jni and napi . It is all right to call C++ and Java through jni from js code, but when I try to call js code from java through jni , it crashes with code 11 and seem as the cached napi_env is not available and I get the information from node documentation that reuse of  napi_env is not allowed. I refered the nodejs-mobile-react-native but not so clear so could anyone tell me how to reuse napi_env or call js function without napi_env ?

**Comment by jaimecbernardo** [comment]
`napi_env` gets saved here: https://github.com/JaneaSystems/nodejs-mobile-react-native/blob/651425964f77a0520ba7c34c7cd6783b0ac1b6cf/android/src/main/cpp/rn-bridge.cpp#L236

It seems to work. Also, you can try to call the bridge channels directly from Java and see if that works.

**Comment by lilulu2018** [comment]
@jaimecbernardo Thanks I will have a try
