### ISSUE TITLE
Add requiresMainQueueSetup method

### ISSUE THREAD

**Issue by rayronvictor** [janeasystems/nodejs-mobile#28]
* **Version**: 8.9.3
* **Platform**: 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
* **Subsystem**: nodejs-mobile-react-native

Since React-Native 0.49, requiresMainQueueSetup needs to be defined if the module overrides constantsToExport.

Warning: 

> RCTLog.js:48 Module RNNodeJsMobile requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by jaimecbernardo** [comment]
Hi @rayronvictor,
Thank you for the issue.
We were not aware of this and will look into it.

**Comment by jaimecbernardo** [comment]
The fix for this issue landed in https://github.com/janeasystems/nodejs-mobile-react-native/commit/c32ace3e432f9ee29f5c05964f12c966611a5ddf
Thank you for the contribution!
