### ISSUE TITLE
How to run using swift

### ISSUE THREAD

**Issue by JoYeonJeong** [janeasystems/nodejs-mobile#282]
Nodejs mobile usage example uses objective-c language. 
this example: https://github.com/JaneaSystems/nodejs-mobile-samples/tree/master/ios/native-xcode-node-folder

But, I want to use the swift language. 

Does anyone know how to use it?

**Comment by jaimecbernardo** [comment]
Hi @JoYeonJeong , you should be able to call C or C++ functions in Swift, in order to start nodejs-mobile.
