### ISSUE TITLE
doc: Make a react native sample

### ISSUE THREAD

**Issue by markstien** [janeasystems/nodejs-mobile#310]
Hello guys, i am new to this.  i tried to use it in my react native project. And i didn't  make it work. 
Can there  be a react native sample,  so i can learn how to use it.

**Comment by sallespro** [comment]
here you'll find some react-native examples to start. https://github.com/JaneaSystems/nodejs-mobile-samples/tree/master/react-native
pay attention to gradle/pliugin version updates and its dependencies. More info here. https://github.com/JaneaSystems/nodejs-mobile/issues/317#issuecomment-865336405

**Comment by markstien** [comment]
> here you'll find some react-native examples to start. https://github.com/JaneaSystems/nodejs-mobile-samples/tree/master/react-native
> pay attention to gradle/pliugin version updates and its dependencies. More info here. [#317 (comment)](https://github.com/JaneaSystems/nodejs-mobile/issues/317#issuecomment-865336405)

Thanks. But i have already used kotlin😂
