### ISSUE TITLE
os.networkInterface method leads to "uv_interface_addresses returned Unknown system error 13" on android 11

### ISSUE THREAD

**Issue by fra189** [janeasystems/nodejs-mobile#327]
**Project: nodejs-mobile
Version: v0.3.2 (release tag)
Mobile device: Realme GT RMX2022 EUR
Mobile OS and version: Android 11
Development Node.js: v12.19.0
Development platform: Linux ib818 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Android NDK: r21b**

Every access to os.networkInterface leads to uv_interface_addresses unknown system error 13
Code worked until Android 10.

`2021-07-06 16:20:27.696 21451-21703/com.androidjs.sonoffdiy E/nodejs: os.js:63
          throw new ERR_SYSTEM_ERROR(ctx);`

    `SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
        at Object.networkInterfaces (os.js:205:16)
        at allInterfaces (/data/data/com.androidjs.sonoffdiy/files/myapp/node_modules/multicast-dns/index.js:167:21)
        at EventEmitter.that.update (/data/data/com.androidjs.sonoffdiy/files/myapp/node_modules/multicast-dns/index.js:124:63)
        at Socket.<anonymous> (/data/data/com.androidjs.sonoffdiy/files/myapp/node_modules/multicast-dns/index.js:55:12)
        at Socket.emit (events.js:326:22)
        at startListening (dgram.js:150:10)
        at dgram.js:345:7
        at processTicksAndRejections (internal/process/task_queues.js:85:21) {
      code: 'ERR_SYSTEM_ERROR',
      info: {
        errno: 13,
        code: 'Unknown system error 13',
        message: 'Unknown system error 13',
        syscall: 'uv_interface_addresses'
      },
      errno: [Getter/Setter],
      syscall: [Getter/Setter]
    }`

`2021-07-06 16:20:27.698 21451-21571/com.androidjs.sonoffdiy A/libc: FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7aab23c470)
2021-07-06 16:20:27.708 21451-21703/com.androidjs.sonoffdiy E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
2021-07-06 16:20:27.714 21451-21451/? A/libc: FORTIFY: pthread_mutex_trylock called on a destroyed mutex (0x74003e9230)
2021-07-06 16:20:27.708 21451-21703/? E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY) `

Is there something I can do on my side to avoid this?
Thanks

**Comment by jaimecbernardo** [comment]
Hi @fra189 ,
Thank you for reporting this. We've seen this happen in Android 12 but not Android 11, due to the new privacy restrictions.
What's the build version for Android 11?
There's a fix in the pipeline for this.

**Comment by fra189** [comment]
Hi @jaimecbernardo 

**Build Number: RMX2202_11_A.9
   Kernel versio: 5.4.61-qgki-g2700c78**

Thank you. It's been a week I try ti get rid of this.
Waiting for the fix to be ready

**Comment by jaimecbernardo** [comment]
Hi @fra189 ,
I've pushed the commit : https://github.com/JaneaSystems/nodejs-mobile/commit/73d5d375dbd672c3df8556a83ad122a078d21ed2

Please let me know how it goes. You'll have to build the library, though.
It could still be some time until the next release.

**Comment by fra189** [comment]
Hi @jaimecbernardo 
Many thanks.
Starting now the build.

A little update:
After your answer about android 11/12 (that gave me a more specific target), I investigated a little.
About Android 11 (API 30) there is the workaround: keep target API to 29 (Android 10) and add 
` android:requestLegacyExternalStorage="true"`
in "application" section of the manifest as documented here:
[https://developer.android.com/about/versions/11/privacy/storage](url)
This grants needed permision to app avoiding the problem for now.

**Comment by fra189** [comment]
Hi @jaimecbernardo 
With this gradle settings (note targetSdkVersion :) )

**ndkVersion '21.1.6352462'
minSdkVersion 21
targetSdkVersion 30**

Compilation is succesful and I'm able to use os.networkInterfaces 
Thank you
