### ISSUE TITLE
package com.janeasystems.rn_nodejs_mobile does not exist

### ISSUE THREAD

**Issue by mHart1000** [janeasystems/nodejs-mobile#33]
* **Version**: 6.11
* **Platform**: Windows 7 64 bit
* **Subsystem**:

I cloned the sample react native project, ran install and link, and opened the android folder in android studio to let it install all dependencies. But when I try to run-android the build fails. Running gradlew clean builds succesfully, but doesn't fix the problem.

Any help is greatly appreciated! 

In trying to run the sample project on android, the build fails with the error:

:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

C:\Users\Matthew\Desktop\Awe\suspendresume\android\app\src\main\java\com\suspendresume\MainApplication.java:6: error: package com.janeasystems.rn_nodejs_mobile does not exist
import com.janeasystems.rn_nodejs_mobile.RNNodeJsMobilePackage;
                                        ^

C:\Users\Matthew\Desktop\Awe\suspendresume\android\app\src\main\java\com\suspendresume\MainApplication.java:27: error: cannot find symbol
            new RNNodeJsMobilePackage()
                ^

  symbol: class RNNodeJsMobilePackage
2 errors
:app:compileDebugJavaWithJavac FAILED

**Comment by jaimecbernardo** [comment]
Hi @mHart1000 , thank you for the issue.

From the error you got, it seems that the main react-native application is unable to find the `nodejs-mobile-react-native` Java package at compile time, so I think something went wrong while running `react-native link`.

I've been able to get the same error you got by deleting the `compile project(':nodejs-mobile-react-native')` line that should be in `dependencies` inside `suspendresume/android/app/build.gradle` and by deleting the following lines from `suspendresume/android/settings.gradle`:
```
include ':nodejs-mobile-react-native'
project(':nodejs-mobile-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/nodejs-mobile-react-native/android')
```

Could you please verify if those lines are present in the mentioned files? `react-native link` might've not put those there.

Another way to try to run `react-native run-android` from a clean state is by making sure `Android Studio` is closed and deleting the following folders:
- `suspendresume/android/app/build/`
- `suspendresume/android/build/`
- `suspendresume/node_modules/nodejs-mobile-react-native/android/build/`
- `suspendresume/node_modules/nodejs-mobile-react-native/android/.externalNativeBuild/`

I hope this is helpful.
In case it doesn't work, would you mind sharing what versions of `react-native`, `Android Studio` and `Android SDK` components you have installed?

**Comment by mHart1000** [comment]
Thank you very much for your response! 

The lines mentioned were present in the settings.gradle file, but not in the build.gradle file. Adding them fixed the error both in the example project and my own project. 

In my project though, the initial screen loads okay, but when I try to do perform an action that uses the node server (a get request to a database running as a separate process on my machine), I get a 'network request failed' error and the app minimizes and resets itself.

I've added the import and componentWillMount lines to app.js, and copied my node project into the nodejs-project folder and renamed the root as main.js. Is there anything else I would need to change in the node or react files that were working before when run as separate processes?

**Comment by jaimecbernardo** [comment]
From your description, it seems like the conditions to run the `nodejs-project` are met (`main.js` and `package.json` inside `nodejs-project` and react-native calls the `nodejs.start()` method).

I couldn't quite understand your scenario, though. The app seems to be failing due to the uncaught exception in the `nodejs-project` part.

Would you be able to give more details or provide a project repo where we could replicate the issue? I'd like to invite you to join our [gitter channel](https://gitter.im/nodejs-mobile/community).

Thank you, in advance.

**Comment by jaimecbernardo** [comment]
This issue has been open for a while and was about getting started, so I'm closing it.

**Comment by marciocamello** [comment]
Change slashes in windows to double slashs

project(':nodejs-mobile-react-native').projectDir = new File(rootProject.projectDir, '..\\node_modules\\nodejs-mobile-react-native\\android')

**Comment by jaimecbernardo** [comment]
Hi @marciocamello ,

Did that solve a similar issue in your case?
Those lines are added by the react-native utility when running `react-native link`, so it'd be an issue in react-native.
Gradle is supposed to support forward slashes on Windows and convert them internally as needed.
