### ISSUE TITLE
Could i use Node version 16 instead?

### ISSUE THREAD

**Issue by nguyenthanhsonbs** [janeasystems/nodejs-mobile#338]
Hi, could i use Node Version 16 instead. Now it's only 12. Thanks you all

**Comment by frank-dspeed** [comment]
@sohushare short answer no you can not. This is a Fork of NodeJS it needs to port its changes on top of the NodeJS main repo.

You need to wait and can only use the offered NodeJS version

**Comment by nguyenthanhsonbs** [comment]
Thanks you for that
