### ISSUE TITLE
Strange network behaviour

### ISSUE THREAD

**Issue by bushev** [janeasystems/nodejs-mobile#35]
* **Version**: v8.9.4
* **Platform**: Darwin YMBR.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

We have created a repository (https://github.com/Rudimo/ionic-nodejs-mobile-cordova) with reproduction of a strange network problem. In short: first tcp/ip connection from Node.js process always fails sometimes. See [Node.js file](https://github.com/Rudimo/ionic-nodejs-mobile-cordova/blob/master/src/nodejs-project/index.js) to get more info about testing scenarios.

### Fail scenario

1. Start the app
2. Click "connect-without-tcp-ping"
3. Expected: "Connection was successfully established"
4. Actual: Connection fails with a timeout error
![image](https://user-images.githubusercontent.com/7535766/34744635-f12e5ae4-f59e-11e7-9224-b0830fa91246.png)

### Success scenario (with a workaround)

1. Start the app (stop app before, it's **important**)
2. Click "connect-after-tcp-ping"
3. Expected: Ping is OK and "Connection was successfully established"
4. Actual: Ping fails but connection is OK
![image](https://user-images.githubusercontent.com/7535766/34744691-224436f8-f59f-11e7-9826-4a786034db46.png)

We are prepared APK file - [android-debug.apk](https://github.com/Rudimo/ionic-nodejs-mobile-cordova/blob/master/android-debug.apk). Setup MongoDB on `192.168.1.36:27025` before resting.

**Comment by bushev** [comment]
Wrapping every call `on('message', ...` in a `setImmediate()` helps me. Thank guys!

**Comment by jaimecbernardo** [comment]
Thank you for the issue and for taking the time in helping understand it.
For anyone who reads this issue later, it is related to https://github.com/janeasystems/nodejs-mobile/issues/13 and could be solved the same way.
