### ISSUE TITLE
CopyFile ios

### ISSUE THREAD

**Issue by TheNoim** [janeasystems/nodejs-mobile#37]
* **Version**: `v8.6.0-pre`
* **Platform**: `Darwin Noim 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:14:50 PDT 2017; root:xnu-4570.20.62~4/RELEASE_ARM64_T8010 iPhone9,4 arm64 D111AP Darwin`
* **Subsystem**: `fs`

CopyFile dosen't work correctly on ios. 

![bad_system_call](https://user-images.githubusercontent.com/5133056/35062892-cb829fda-fbc5-11e7-90fc-c74a093e7622.png)

Just an example copyFileSync.
This prevents the usage of npm or yarn. 

`ENOSYS: function not implemented, copyfile`

**Comment by jaimecbernardo** [comment]
Hi @TheNoim, thank you for the issue.
We've verified that both `fs.copyFile` and `fs.copyFileSync` are not working correctly on iOS.
We will look into it.

**Comment by jaimecbernardo** [comment]
Hi @TheNoim ,

This is fixed in this commit: https://github.com/janeasystems/nodejs-mobile/commit/5b286e16a5bc88ac9f84d8a0910b9b8eefb18042

If you are able to build it, please let us know if this fixes your issue.

**Comment by TheNoim** [comment]
Thanks, it is fixed.
