### ISSUE TITLE
js call oc?

### ISSUE THREAD

**Issue by ilioner** [janeasystems/nodejs-mobile#39]
* **Version**:
* **Platform**:
* **Subsystem**:

Hi.How to call a function from js to oc?

**Comment by jaimecbernardo** [comment]
Hi @ilioner ,

I'm not quite sure what your exact question is, but I'm guessing your asking about calling from `node-mobile`'s javascript code into `ObjectiveC`. I hope this is correct.

The `nodejs-mobile` core library doesn't provide any built-in method for this, but we've had success in doing it by means of Pipes / IP servers.
For the `react-native` and `cordova` plugins we've built a native code module in `N-API` to build a bridge that can send and receive strings in a event based fashion to the native code and then the UI layer. More details about that can be seen in the discussion to this issue:
https://github.com/janeasystems/nodejs-mobile/issues/4

I hope this is helpful.
I'd like to invite you to join our community chat gitter, as well, as it might be a better form for questions/answers: https://gitter.im/nodejs-mobile/community

**Comment by jaimecbernardo** [comment]
This issue has been open for a while and was about getting started, so I'm closing it.
