### ISSUE TITLE
Unable to resolve module fs in react native?

### ISSUE THREAD

**Issue by bitabs** [janeasystems/nodejs-mobile#40]
Hi there,

I noticed a similar issue was raised earlier, however it was targeting file writers. In my situation, I'm currently trying to use ***[`openbci-cyton`](https://github.com/openbci/openbci_nodejs_cyton)*** which is a node module.

Now I've followed a basic example of the usage here, but the error is immediately thrown when I try to pass `openbci-cyton` . Here's what I've got so far:

**`ReactNativeComponent.js`**
```js
...
import nodejs from 'nodejs-mobile-react-native';

export default class LaunchScreen extends PureComponent<*, State> {
  constructor(props) {
    super(props);
  }

  componentWillMount() {
    nodejs.start("main.js");
    nodejs.channel.addListener(
      "message",
      (msg) => {
        alert("From node: " + msg);
      },
      this 
    );
  }
}
```
**main.js**
```js
var rn_bridge = require('rn-bridge');
var fs = require('fs');
var Cyton = require('openbci-cyton');

// Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  rn_bridge.channel.send(msg);
});

rn_bridge.channel.send("Node was initialized.");
// Inform react-native node is initialized.
rn_bridge.channel.send("Node was initialized.");
```

when I run this I get the following error:

> error: bundling failed: Error: Unable to resolve module `fs` from `C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\serialport\lib\serialport.js`: Module does not exist in the module map

>This might be related to https://github.com/facebook/react-native/issues/4968
>To resolve try the following:
  >1. Clear watchman watches: `watchman watch-del-all`.
  >2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  >3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  
  >4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`. at ModuleResolver.resolveDependency (C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:313:1719)
    at ResolutionRequest.resolveDependency (C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:97:16)
    at DependencyGraph.resolveDependency (C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\node-haste\DependencyGraph.js:269:4352)
    at C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\DeltaBundler\traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\DeltaBundler\traverseDependencies.js:256:306)
    at C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\DeltaBundler\traverseDependencies.js:256:536
    at new Promise (<anonymous>)
    at C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\DeltaBundler\traverseDependencies.js:256:217
    at addDependency (C:\King's_College_London\Final_Year_Project\HeartFailure\node_modules\metro\src\DeltaBundler\traverseDependencies.js:256:92)

Let me please also clarify that `openbci-cyton`  basically returns data that I want to show in react native, so this whole issue is about how I can:
1. connect `openbci-cyton` module to react native
2. show the data from `openbci-cyton` in react native

**Comment by jaimecbernardo** [comment]
Hi @NaseebullahSafi , thank you for your issue.
From what I see, you are trying to require and pass the `Cyton` module from `react-native` to `nodejs-mobile` through the bridge, but the bridge is only built for passing strings.

My advice would be to require and execute all `Cyton` related operations on `nodejs-mobile` side, as it seems to be a module that requires `fs`, and using the bridge as a way to pass commands and get results from cyton with your own app-defined protocol.

I hope this was helpful.

**Comment by bitabs** [comment]
Thank you @jaimecbernardo I actually realised this just before your comment, and really appreciate your help. However doing that, My app crashes instantly when I require openbci-cyton in main.js. I have updated my main.js. Please do let me know why it crashes. As you can see, just requiring the module crashes my app. Have no idea really.

**Comment by jaimecbernardo** [comment]
Hi @NaseebullahSafi .
How is your app crashing currently? Do you have any logs from logcat, for example?

**Comment by jaimecbernardo** [comment]
I'd also like to invite you to join our community chat: https://gitter.im/nodejs-mobile/community
It's probably a more appropriate format for questions/answers.
Thanks, in advance.

**Comment by gigadeplex** [comment]
I'm having the same problem! I cannot load any module except for the native nodejs modules or  any ".node" file.  in my main.js. The app loads successfully for 1 sec but then crashes.  It does not log anything in react-native log-android so how can I debug it?

**Comment by jaimecbernardo** [comment]
Hi @eviansplash , thanks for the question.

In @NaseebullahSafi 's case, logging the application running with `adb logcat -s "NODEJS-MOBILE"`, to get the ouput that comes from `nodejs-mobile`, helped to debug what's going on.

I'd also like to invite you to join our community chat: https://gitter.im/nodejs-mobile/community
It's probably a more appropriate format for questions/answers.

I hope this was helpful.

**Comment by jaimecbernardo** [comment]
This issue has been open for a while and was about getting started, so I'm closing it.
