### ISSUE TITLE
Support for Xamarin Platform

### ISSUE THREAD

**Issue by tangkhaiphuong** [janeasystems/nodejs-mobile#41]
Please support binding for Xamarin Platform
- Android
- iOS

**Comment by jaimecbernardo** [comment]
Hi @tangkhaiphuong , thank you for the issue.

We're currently focusing on supporting `cordova` and `react-native` plugins, only, as these frameworks are built around the same language as the node runtime (JavaScript).
While there are no current plans for Xamarin support, we're open to community contributions for supporting other frameworks and accept PRs.

Please let us know if you give it a try.

I hope this was helpful.

**Comment by jaimecbernardo** [comment]
Closing this issue, as support for Xamarin is currently not planned.
