### ISSUE TITLE
Best approach for using multiple JS files in Android project

### ISSUE THREAD

**Issue by roomofdoom** [janeasystems/nodejs-mobile#44]
Hi,

I have a large project that I would like to test on the Android side, it's a Express based server but has quite a lot of files.

I have a basic Android example up and running (based on nodejs-mobile-samples) but having trouble with including more than one JS files.  So far I have added one JS file as a raw resource file which is then read into a string for _startNodeWithArguments_.  One file works fine, but there's no way to require other files from within the JS code.

What would be the best way to go about including JS project files into the APK for execution - and including them in JS using _require_?

This is how I'm using one JS file at the moment (file is named raw.js - hence R.raw.raw)

```       
        InputStream is = this.getResources().openRawResource(R.raw.raw);
        BufferedReader br = new BufferedReader(new InputStreamReader(is));
        String readLine = null;
        String code = "";
        try {
            // While the BufferedReader readLine is not null
            while ((readLine = br.readLine()) != null) {
                Log.d("TEXT", readLine);
                code += readLine;
            }
            is.close();
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        final String fCode = code;

        if (!_startedNodeAlready) {
            _startedNodeAlready = true;
            new Thread(new Runnable() {
                @Override
                public void run() {
                    startNodeWithArguments(new String[]{"node", "-e",
                            fCode
                    });
                }
            }).start();
        }
```

**Comment by jaimecbernardo** [comment]
Hi @roomofdoom , thank you for the issue.

The main problem with Android is that the APK is essentially an archive file while the node runtime expects to be run on an environment with actual paths.

In terms of strategies to get around this, the `nodejs-mobile-cordova` and `nodejs-mobile-react-native` plugins expect the node code and modules to be on a project folder, added to the App's assets, which is copied to the App's document folder at runtime.

This code can be checked on either plugin: https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/android/src/main/java/com/janeasystems/rn_nodejs_mobile/RNNodeJsMobileModule.java for `react-native` or https://github.com/janeasystems/nodejs-mobile-cordova/blob/4fe04f39f731cf74139749b8675b2f68ba7d6642/src/android/java/com/janeasystems/cdvnodejsmobile/NodeJS.java for `cordova`.

The current version of this strategy first creates lists with the folder and file structure at build time so the copy is faster later on: https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/android/build.gradle#L60-L85 for `react-native` or https://github.com/janeasystems/nodejs-mobile-cordova/blob/4fe04f39f731cf74139749b8675b2f68ba7d6642/install/hooks/android/before-build.js for `cordova`.

There may be other strategies for this, depending on your application's requirements.

I hope this was helpful.

**Comment by jaimecbernardo** [comment]
This issue has been open for a while and was about getting started, so I'm closing it.
