### ISSUE TITLE
Support for child_process

### ISSUE THREAD

**Issue by enagic** [janeasystems/nodejs-mobile#47]
nodejs-mobile-cordova@0.1.1

It seems that nodejs is is capable of multi-threading, but the "cluster" module is dependent on the "child_process" module along with the actual node binary to be able to spawn a new instance of node.  Given that this node instance isn't executed natively (if I understand correctly), is there a technical way to be able to multi-thread?

**Comment by jaimecbernardo** [comment]
Hi @enagic , Thank you for the issue.

There's an issue already open regarding child processes: https://github.com/janeasystems/nodejs-mobile/issues/25

The idea behind cluster is that it will spawn multiple processes (not threads), which is not allowed by `iOS`, but could in theory work on `Android`, if you're using `node-mobile` as a standalone application, or embed it in a format that would enable new processes and forking. Can't think of a way to make this work with Cordova, however.

Regarding Multithreading, Node.js has been designed with the assumption that there will be a single Javascript engine thread per process, so it uses `libuv` to start threads to wait on lengthier operations. Node.js modules can also start threads and then use `libuv` to call back into the Javascript engine thread. The current bridge is implemented this way (calling into the Node.js thread from the UI or native threads). As far as I know, there's no built-in way in Node.js to start other threads, only processes.

I hope this was helpful.

**Comment by enagic** [comment]
I wasn't aware of the existing "issue"... maybe I was searching with the wrong key words, though I wouldn't really consider it an issue at all.

I can fully agree that it would be a good idea to maintain parity between iOS and Android (otherwise, there's really no purpose for this project).  That said, it looks like using projects like Gulp/Grunt may be out of the question (unless they provide an API that doesn't kill itself, which I haven't currently found).  Perhaps I'll have better luck with Webpack.

Thanks.

**Comment by jaimecbernardo** [comment]
We've had a sample contribution that uses Gulp: https://github.com/janeasystems/nodejs-mobile-samples/tree/e1039615a12b843a5e5b4539ea42f07f6ec2a9eb/cordova-angularjs

The most common workflow with these tools seems to be to use them at build time, and then include the resulting bundle with your application. Though your requirements might need them at runtime.

I hope this was helpful.

**Comment by enagic** [comment]
Indeed that is the case... I am trying to create a build as a service.  But looks like I'm in good hands with Webpack, which seems to be the direction the community is going anyhow.

Thanks.
