### ISSUE TITLE
Cordova-android: not able to get nodejs

### ISSUE THREAD

**Issue by sumitchhnn** [janeasystems/nodejs-mobile#52]
I've created a sample for cordova android following the steps mentioned in:
https://github.com/janeasystems/nodejs-mobile-cordova

But instead of ios i used android.
When i try to run "cordova run android" getting error:
Uncaught ReferenceError: nodejs is not defined
    at startNodeProject (index.js:45)
    at Object.onDeviceReady (index.js:13)
    at Channel.fire (cordova.js:846)
    at cordova.js:231

here is the attached png for the same:

![issue](https://user-images.githubusercontent.com/18306574/37211244-54960ab8-23d1-11e8-818d-cbf16395d621.png)

**Comment by jaimecbernardo** [comment]
Hi @sumitchhnn , Thank you for the question.

The `nodejs` name should be accessible by the cordova UI runtime if the plugin has been installed and is being included in the application. Try to run this again:
```sh
cordova plugin add nodejs-mobile-cordova
cordova build android
cordova run android
```

If this doesn't work, could you please provide more information, like what version of `nodejs-mobile-cordova`, `cordova` and `cordova-android` you are using? A repository with your project might also be useful.

I hope this is helpful. Let us know if it solves your issue.

Edit: By the way, results in the Browser won't be very helpful, since the plugin uses native code, which won't be available in the Browser.

**Comment by sumitchhnn** [comment]
Hi @jaimecbernardo , i tried your mentioned steps but issue still persists.

Regarding the configuration, i am using the following configuration: 
```
cordova version: 7.0.0
nodejs-mobile-cordova: 0.1.4
cordova-andoird: 6.2.3
```
Repository url: [https://github.com/sumitchhnn/nodejs-mobile](url)

**Comment by jaimecbernardo** [comment]
Hi @sumitchhnn ,

Thank you for the repo.
I've tried your sample and it works as expected. Here are the commands I'm running with my Android device connected to a macOS:

```sh
git clone https://github.com/sumitchhnn/nodejs-mobile cordova-sample-sumitchhnn
cd cordova-sample-sumitchhnn/
npm install
cordova platform add android
cordova run android
```

I'm able to see the expected log messages in a logcat window on Android Studio:
```
E/NODEJS-MOBILE: [INFO:CONSOLE(39)] "Node.js Mobile Engine Started", source: file:///android_asset/www/js/index.js (39)
E/NODEJS-MOBILE: [INFO:CONSOLE(32)] "[cordova] received: Replying to this message: Hello from Cordova!", source: file:///android_asset/www/js/index.js (32)
```

So the issue doesn't seem to be with your project.
Could you please provide instructions on how you are running the project from your repo so I can follow them?

**Comment by sumitchhnn** [comment]
I am sorry, i forgot to mention the environment. Actually environment on which i've tested are ubuntu and windows. 
When i try to run same commands on these environment for android application i am facing the issue.

**Comment by jaimecbernardo** [comment]
Could you please provide the Android logcat contents for the error you're getting? Thanks, in advance.

**Comment by sumitchhnn** [comment]
`Android logcat
I/CordovaActivity(31197): Apache Cordova native platform version 6.2.3 is starting

D/CordovaActivity(31197): CordovaActivity.onCreate()

I/GAV2    (31124): Thread[GAThread,5,main]: No campaign data found.

W/linker  (31197): libwebviewchromium.so: unused DT entry: type 0x6ffffffe arg 0x127e4

W/linker  (31197): libwebviewchromium.so: unused DT entry: type 0x6fffffff arg 0x3

I/WebViewFactory(31197): Loading com.google.android.webview version 62.0.3202.84 (code 320208400)

W/ResourceType(31197): Found multiple library tables, ignoring...

W/ResourceType(31197): Found multiple library tables, ignoring...

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>

I/cr_LibraryLoader(31197): Time to load native libraries: 2 ms (timestamps 3547-3549)

W/ResourceType(31197): Found multiple library tables, ignoring...

I/chromium(31197): [INFO:library_loader_hooks.cc(46)] Chromium logging enabled: level = 0, default verbosity = 0

I/cr_LibraryLoader(31197): Expected native library version number "62.0.3202.84", actual native library version number "62.0.3202.84"

I/cr_BrowserStartup(31197): Initializing chromium process, singleProcess=true

I/Adreno-EGL(31197): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030_msm8226_LA.BF.1.1.1_RB1__release_AU ()

I/Adreno-EGL(31197): OpenGL ES Shader Compiler Version: E031.25.03.06

I/Adreno-EGL(31197): Build Date: 06/10/15 Wed

I/Adreno-EGL(31197): Local Branch: 

I/Adreno-EGL(31197): Remote Branch: quic/LA.BF.1.1.1_rb1.24

I/Adreno-EGL(31197): Local Patches: NONE

I/Adreno-EGL(31197): Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030 + 6151be1 +  NOTHING

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$6>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$6>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>

I/art     (31197): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>

D/SystemWebViewEngine(31197): CordovaWebView is running on device made by: Sony

E/chromium(31197): [ERROR:devtools_http_handler.cc(249)] Cannot start http server for devtools. Stop devtools.

D/PluginManager(31197): init()

D/CordovaWebViewImpl(31197): >>> loadUrl(file:///android_asset/www/index.html)

W/cr_media(31197): Requires BLUETOOTH permission

D/CordovaActivity(31197): Started the activity.

D/CordovaActivity(31197): Resumed the activity.

D/OpenGLRenderer(31197): Use EGL_SWAP_BEHAVIOR_PRESERVED: true

D/Atlas   (31197): Validating map...

V/WindowManager(  862): Adding window Window{198e508d u0 io.cordova.hellocordova/io.cordova.hellocordova.MainActivity} at 5 of 12 (before Window{21c9f571 u0 Starting io.cordova.hellocordova})

I/art     (17290): Explicit concurrent mark sweep GC freed 163(8KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 845us total 57.495ms

I/OpenGLRenderer(31197): Initialized EGL, version 1.4

D/OpenGLRenderer(31197): Enabling debug mode 0

I/ActivityManager(  862): Displayed io.cordova.hellocordova/.MainActivity: +1s294ms

I/Timeline(  862): Timeline: Activity_windows_visible id: ActivityRecord{195aae83 u0 io.cordova.hellocordova/.MainActivity t3506} time:190304382

W/cr_CrashFileManager(31197): /data/data/io.cordova.hellocordova/cache/WebView/Crash Reports does not exist or is not a directory

I/Timeline(31197): Timeline: Activity_idle id: android.os.BinderProxy@9d5d29e time:190304439

D/CordovaWebViewImpl(31197): onPageDidNavigate(file:///android_asset/www/index.html)

I/eLock   (17290): pkgname_before:com.sonyericsson.home  class:io.cordova.hellocordova  isFingerActivityCreated:false   isCalling:false

W/AlarmManager(  862): Suspiciously short interval 300 millis; expanding to 60 seconds

E/libEGL  (31197): validate_display:255 error 3008 (EGL_BAD_DISPLAY)

W/AudioCapabilities(31197): Unsupported mime audio/evrc

W/AudioCapabilities(31197): Unsupported mime audio/qcelp

W/VideoCapabilities(31197): Unrecognized profile 2130706433 for video/avc

W/AudioCapabilities(31197): Unsupported mime audio/qcelp

W/AudioCapabilities(31197): Unsupported mime audio/evrc

W/VideoCapabilities(31197): Unsupported mime video/divx

W/VideoCapabilities(31197): Unsupported mime video/divx311

W/VideoCapabilities(31197): Unsupported mime video/divx4

I/VideoCapabilities(31197): Unsupported profile 4 for video/mp4v-es

E/chromium(31197): [ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::BudgetService exposed by: content_browser

D/JsMessageQueue(31197): Set native->JS mode to EvalBridgeMode

E/chromium(31197): [ERROR:BudgetService.cpp(167)] Unable to connect to the Mojo BudgetService.

D/CordovaWebViewImpl(31197): onPageFinished(file:///android_asset/www/index.html)

D/SystemWebChromeClient(31197): file:///android_asset/www/js/index.js: Line 25 : Received Event: deviceready

I/chromium(31197): [INFO:CONSOLE(25)] "Received Event: deviceready", source: file:///android_asset/www/js/index.js (25)

D/SystemWebChromeClient(31197): file:///android_asset/www/js/index.js: Line 45 : Uncaught ReferenceError: nodejs is not defined

I/chromium(31197): [INFO:CONSOLE(45)] "Uncaught ReferenceError: nodejs is not defined", source: file:///android_asset/www/js/index.js (45)

I/art     (17290): Explicit concurrent mark sweep GC freed 274(27KB) AllocSpace objects, 1(16KB) LOS objects, 39% free, 11MB/19MB, paused 1.076ms total 94.981ms

I/art     (17290): Explicit concurrent mark sweep GC freed 103(5KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 988us total 58.105ms

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1346: Failed to get TransState, rc 

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/art     (17290): Explicit concurrent mark sweep GC freed 83(4KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 814us total 63.220ms

I/art     (17290): Explicit concurrent mark sweep GC freed 83(4KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 826us total 62.341ms

I/art     (17290): Explicit concurrent mark sweep GC freed 83(4KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 1.659ms total 78.024ms

D/Ulp_jni (  862): Location CB invoked

D/TelephonyIcons( 1418): updateDataType sub=0, type=10, inetCondition=1 showAtLeast3G=false show4GforLte=false hspaDistinguishable=true

D/TelephonyIcons( 1418): data type item name: array/telephony_data_type_sim1 roaming item name:array/telephony_roaming_data_type_sim1animation roaming item name: array/telephony_animation_roaming_data_type_sim1

D/TelephonyIcons( 1418): data type item id: 2131230726 roaming item id:2131230729animation roaming itme id: 2131230732

D/TelephonyIcons( 1418): updateDataType mSelectedDataTypeIcon[0]=2130837932, mSelectedRoamingDataTypeIcon=2130837937 mSelectedAnimationRoamingDataTypeIcon=2130837933 mSelectedDataActivityIndex=6

D/TelephonyIcons( 1418): getSignalStrengthIcon: sub=0, inetCondition=1, level=4 isRoaming=false

D/TelephonyIcons( 1418): signalStrengthArray.length = 9

D/TelephonyIcons( 1418): selectedTypeArray.length = 2

D/TelephonyIcons( 1418): inetArray.length = 5

I/WifiHAL (  862): Poll result = 1

I/WifiHAL (  862): Found some events!!!

D/WifiHAL (  862): no_seq_check received

I/WifiHAL (  862): event received NL80211_CMD_TRIGGER_SCAN

I/WifiHAL (  862): event received NL80211_CMD_TRIGGER_SCAN, vendor_id = 0x0

I/WifiHAL (  862): event ignored!!

I/art     (17290): Explicit concurrent mark sweep GC freed 80(3KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 11MB/19MB, paused 723us total 59.190ms

I/WifiHAL (  862): Poll result = 1

I/WifiHAL (  862): Found some events!!!

D/WifiHAL (  862): no_seq_check received

I/WifiHAL (  862): event received NL80211_CMD_NEW_SCAN_RESULTS

I/WifiHAL (  862): event received NL80211_CMD_NEW_SCAN_RESULTS, vendor_id = 0x0

I/WifiHAL (  862): event ignored!!

I/art     (17290): Explicit concurrent mark sweep GC freed 76(3KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 919us total 68.238ms

I/art     (17290): Explicit concurrent mark sweep GC freed 52(2432B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 927us total 67.016ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 917us total 66.905ms

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1346: Failed to get TransState, rc 

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 2.371ms total 95.879ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 1.223ms total 58.972ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 1.085ms total 82.191ms

D/Ulp_jni (  862): Location CB invoked

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 1.001ms total 64.751ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 1.305ms total 78.575ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 920us total 68.132ms

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1346: Failed to get TransState, rc 

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 817us total 65.455ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 804us total 66.400ms

I/CastDatabase( 2418): Saving the database

I/SQLiteCastStore( 2418): [CastNetworkInfo] saved: 0, skipped: 0, [CastDeviceInfo]: saved 0, skipped 0, Paired Guest Mode DeviceInfo] saved: 0, skipped: 0.

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 1.193ms total 77.436ms

D/TelephonyIcons( 1418): updateDataType sub=0, type=10, inetCondition=1 showAtLeast3G=false show4GforLte=false hspaDistinguishable=true

D/TelephonyIcons( 1418): data type item name: array/telephony_data_type_sim1 roaming item name:array/telephony_roaming_data_type_sim1animation roaming item name: array/telephony_animation_roaming_data_type_sim1

D/TelephonyIcons( 1418): data type item id: 2131230726 roaming item id:2131230729animation roaming itme id: 2131230732

D/TelephonyIcons( 1418): updateDataType mSelectedDataTypeIcon[0]=2130837932, mSelectedRoamingDataTypeIcon=2130837937 mSelectedAnimationRoamingDataTypeIcon=2130837933 mSelectedDataActivityIndex=6

D/TelephonyIcons( 1418): getSignalStrengthIcon: sub=0, inetCondition=1, level=4 isRoaming=false

D/TelephonyIcons( 1418): signalStrengthArray.length = 9

D/TelephonyIcons( 1418): selectedTypeArray.length = 2

D/TelephonyIcons( 1418): inetArray.length = 5

D/Ulp_jni (  862): Location CB invoked

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 803us total 64.173ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 821us total 68.469ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 862us total 64.104ms

I/rmt_storage(  302): rmt_storage_connect_cb: clnt_h=0xa2 conn_h=0xb8856518

I/rmt_storage(  302): rmt_storage_rw_iovec_cb: /boot/modem_fs2: clnt_h=0x2: req_h=0xa6 msg_id=3: R/W request received

I/rmt_storage(  302): wakelock acquired: 1, error no: 42

I/rmt_storage(  302): rmt_storage_client_thread: /boot/modem_fs2: clnt_h=0x2 Unblock worker thread (th_id: -1228169216)

I/rmt_storage(  302): rmt_storage_client_thread: /boot/modem_fs2: clnt_h=0x2: req_h=0xa6 msg_id=3: Bytes written = 1572864

I/rmt_storage(  302): rmt_storage_client_thread: /boot/modem_fs2: clnt_h=0x2: req_h=0xa6 msg_id=3: Send response: res=0 err=0

I/rmt_storage(  302): rmt_storage_client_thread: /boot/modem_fs2: clnt_h=0x2 About to block rmt_storage client thread (th_id: -1228169216) wakelock released: 1, error no: 0

I/rmt_storage(  302): 

I/rmt_storage(  302): rmt_storage_disconnect_cb: clnt_h=0x0xa2 conn_h=0x0xb8856518

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 825us total 64.663ms

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1346: Failed to get TransState, rc 

I/Gobi    (  340): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1920: GetTransState() EBADF

D/TelephonyIcons( 1418): updateDataType sub=0, type=10, inetCondition=1 showAtLeast3G=false show4GforLte=false hspaDistinguishable=true

D/TelephonyIcons( 1418): data type item name: array/telephony_data_type_sim1 roaming item name:array/telephony_roaming_data_type_sim1animation roaming item name: array/telephony_animation_roaming_data_type_sim1

D/TelephonyIcons( 1418): data type item id: 2131230726 roaming item id:2131230729animation roaming itme id: 2131230732

D/TelephonyIcons( 1418): updateDataType mSelectedDataTypeIcon[0]=2130837932, mSelectedRoamingDataTypeIcon=2130837937 mSelectedAnimationRoamingDataTypeIcon=2130837933 mSelectedDataActivityIndex=6

D/TelephonyIcons( 1418): getSignalStrengthIcon: sub=0, inetCondition=1, level=4 isRoaming=false

D/TelephonyIcons( 1418): signalStrengthArray.length = 9

D/TelephonyIcons( 1418): selectedTypeArray.length = 2

D/TelephonyIcons( 1418): inetArray.length = 5

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 807us total 61.193ms

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 821us total 76.216ms

D/TelephonyIcons( 1418): updateDataType sub=0, type=10, inetCondition=1 showAtLeast3G=false show4GforLte=false hspaDistinguishable=true

D/TelephonyIcons( 1418): data type item name: array/telephony_data_type_sim1 roaming item name:array/telephony_roaming_data_type_sim1animation roaming item name: array/telephony_animation_roaming_data_type_sim1

D/TelephonyIcons( 1418): data type item id: 2131230726 roaming item id:2131230729animation roaming itme id: 2131230732

D/TelephonyIcons( 1418): updateDataType mSelectedDataTypeIcon[0]=2130837932, mSelectedRoamingDataTypeIcon=2130837937 mSelectedAnimationRoamingDataTypeIcon=2130837933 mSelectedDataActivityIndex=6

D/TelephonyIcons( 1418): getSignalStrengthIcon: sub=0, inetCondition=1, level=4 isRoaming=false

D/TelephonyIcons( 1418): signalStrengthArray.length = 9

D/TelephonyIcons( 1418): selectedTypeArray.length = 2

D/TelephonyIcons( 1418): inetArray.length = 5

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 957us total 70.366ms

D/Ulp_jni (  862): Location CB invoked

I/WifiHAL (  862): Poll result = 1

I/WifiHAL (  862): Found some events!!!

D/WifiHAL (  862): no_seq_check received

I/WifiHAL (  862): event received NL80211_CMD_TRIGGER_SCAN

I/WifiHAL (  862): event received NL80211_CMD_TRIGGER_SCAN, vendor_id = 0x0

I/WifiHAL (  862): event ignored!!

I/art     (17290): Explicit concurrent mark sweep GC freed 8(256B) AllocSpace objects, 0(0B) LOS objects, 39% free, 11MB/19MB, paused 827us total 61.762ms
`

**Comment by jaimecbernardo** [comment]
Hi @sumitchhnn ,

Thank you for the logs. It's like the plugin isn't installed at all.

I've retried on a Linux machine, making sure I had `cordova 7.0.0` and making sure I used `cordova-android 6.2.3` :
```sh
git clone https://github.com/sumitchhnn/nodejs-mobile cordova-sample-sumitchhnn
cd cordova-sample-sumitchhnn/
npm install
cordova platform add android@6.2.3
cordova run android
```
I still had the expected result.

Are you doing these steps from a clean clone of your sample repo from github?
Any build errors when running `cordova build android` or `cordova run android`?

Try to reinstall the module by running : `cordova plugin remove nodejs-mobile-cordova` and `cordova plugin add nodejs-mobile-cordova` and seeing if there are any errors.

Can you see if in `platforms/android/build.gradle` you can find this snippet:
```groovy
// PLUGIN GRADLE EXTENSIONS START
apply from: "nodejs-mobile-cordova/hellocordova-build.gradle"
// PLUGIN GRADLE EXTENSIONS END
```

Can you see if you can find `NodeJS.java` in `platforms/android/src/com/janeasystems/cdvnodejsmobile/`?

These are some ideas to try to debug what's going on, since I can't seem to replicate the issue. I hope this is helpful and please let me know if you can provide more information.

**Comment by sumitchhnn** [comment]
Thanks @jaimecbernardo for all your help, it seems that issue is with my system configuration.
When i try the same thing on another system, it was working. 

You idea for checking issue during build process works and helps to find out the issue was in my system configuration.

**Comment by jaimecbernardo** [comment]
Glad it was helpful, @sumitchhnn . Closing this issue, then.
By the way, would you mind sharing some details in what the issue with the configuration was?
Thank you for the feedback.
