### ISSUE TITLE
Is it possible to use FOREVER pakage in native ios application  to run server after application close (terminate)

### ISSUE THREAD

**Issue by anshulCreativethoughtsinfo** [janeasystems/nodejs-mobile#53]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by jaimecbernardo** [comment]
Hi @anshulCreativethoughtsinfo ,
It seems the `forever` package depends on spawning new processes for that feature, and spawning new processes is not allowed on iOS, as discussed in other issue in case you want to track it: https://github.com/janeasystems/nodejs-mobile/issues/25 
My initial guess is that it won't work.
