### ISSUE TITLE
Node module folders starting with underscore not copied on Android

### ISSUE THREAD

**Issue by antoniuschan99** [janeasystems/nodejs-mobile#60]
* **Version**: 7.10.0
* **Platform**: x86_64

I am able to get iOS working for a project but have much trouble getting Android working.
It successfully builds, but it seems to not be able to read a file in node_modules which causes the app to crash after launch. The files are there in node_modules too. It seems to have to do with the `_generated_` folder?

Here is the log in logcat

`Node assets copy failed at com.janeasystems.rn_nodejs_mobile.RNNodeJsMobileModule$1.run(RNNodeJsMobileModule.java:86) at java.lang.Thread.run(Thread.java:764) Caused by: java.io.FileNotFoundException: nodejs-project/node_modules/node-opcua-service-read/_generated_/_auto_generated_ReadValueId.js`

**Comment by antoniuschan99** [comment]
I received a reply from @jaimecbernardo in the Gitter chat

Hi @antoniuschan99 , Thank you for reporting it and opening the issue. The aapt (Android Asset Packaging Tool) seems to ignore any folders starting with an underscore, so they end up not being copied to the APK. It must be the `<dir>_*` entry in its source: https://android.googlesource.com/platform/frameworks/base/+/b41af58f49d371cedf041443d20a1893f7f6c840/tools/aapt/AaptAssets.cpp#60

There must be a way to define a different ignore pattern for your Android project, and figuring it out is on our list of TODOs. In the meanwhile, I hope this was helpful and please let us know if you find a solution and if you're on react-native, cordova or pluginless scenario.

**Comment by jaimecbernardo** [comment]
I'll add the workaround that was found for @antoniuschan99 case here. If someone knows of a better/distinct solution that could possibly be made to work just from the plugin, we'd appreciate if you could leave a comment. Thank you, in advance.

As a workaround for the react-native plugin, it's possible to get the paths starting with underscore to be included in the APK, by overriding the Android Asset Packaging Tool ignore pattern for both the react-native application and the plugin, by adding the following:
```
        aaptOptions {
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
```
inside `android {` / `defaultConfig { ` in two gradle files inside your react-native project folder `android/app/build.gradle` and `node_modules/nodejs-mobile-react-native/android/build.gradle`.

The files have similar structures that look something like this:
```
...
android {
    ...
    defaultConfig {
        ...
        aaptOptions {
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
...
}
```
It may be necessary to do a proper gradle clean after these changes before running the application. From the react-native project folder, run:
```
cd android
./gradlew clean
cd ..
react-native run-android
```

This workaround isn't a permanent solution for the plugin. While one of the gradle files involved in the workaround is inside the plugin, the application gradle file is created by react-native, so we'll still have to look for a more permanent solution that doesn't involve editing that file manually.

**Comment by antoniuschan99** [comment]
confirmed this fixes it :)

**Comment by luandro** [comment]
Just wanted to leave noted here the pattern suggested by @jaimecbernardo that worked for me to get [scuttlebot](https://github.com/ssbc/scuttlebot) working:

```
...
android {
    ...
    defaultConfig {
        ...
        aaptOptions {
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
...
}
```

**Comment by jaimecbernardo** [comment]
In @luandro 's case ( https://github.com/janeasystems/nodejs-mobile/issues/60#issuecomment-381288106 ), he had issues with directories starting with underscore (`<dir>_*`) and files starting with dot (`.*`), so he removed both these patterns from the default `ignoreAssetsPattern`.
- Default from aapt: `'!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~'`
- Correct for his case: `'!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~'`

The correct pattern to use depends on the files that are causing issues.

**Comment by Matthcw** [comment]
I confirm that this issue still is the case in 2019, however the workaround still works! Thanks!

**Comment by magalhas** [comment]
This stills happens at of now (2020). It would be nice to include the fix, having to manually change `build.gradle` file inside node_modules is not friendly at all. @jaimecbernardo

**Comment by viniciuscb** [comment]
I am having to make this fix inside node_modules in 2023.

**Comment by lypanov** [comment]
Still required in 2024 to make use of the openai library. Alas couldn't get it working as the gradle files have changed format apparently so rolled my own openai api.
