### ISSUE TITLE
Documentation? Help getting started

### ISSUE THREAD

**Issue by SlayterDev** [janeasystems/nodejs-mobile#61]
So it seems there isn't a whole lot of documentation available for integrating this project unless I'm missing it somewhere. I've followed the getting started for iOS which is working perfectly but I have several questions that that document doesn't answer.

~How can I hook into the console out put from node to display it?~ ~Figured this out. But how can I route the console output from stdout to say a textview?~

Is there any info on getting npm running inside an iOS app?

Thank you for any info.

**Comment by jaimecbernardo** [comment]
Hi @SlayterDev ,

Regarding console output, node' console uses the `stdout` and `stderr` streams, so redirecting them through pipes in your application could be a strategy to accomplish it. Other ways may be setup for communication with the node runtime, like starting a background webserver, opening a pipe or building a more complex in process communication scheme. The native library scenario doesn't come with any built-in mechanism for this, but in the react-native and cordova plugins there's a "bridge" to pass strings around that you can try to emulate.

Using the cordova implementation as an example, it is a node native module, which C++ code is defined here: https://github.com/janeasystems/nodejs-mobile-cordova/tree/1143e2080de27cdeb587b42d9187e6254ab46634/src/common/cordova-bridge
The JS code is here: https://github.com/janeasystems/nodejs-mobile-cordova/blob/1143e2080de27cdeb587b42d9187e6254ab46634/install/nodejs-mobile-cordova-assets/builtin_modules/cordova-bridge/index.js
Here's the part that receives messages from the node runtime: https://github.com/janeasystems/nodejs-mobile-cordova/blob/1143e2080de27cdeb587b42d9187e6254ab46634/src/ios/CDVNodeJS.mm#L24-L27 which is registered here: https://github.com/janeasystems/nodejs-mobile-cordova/blob/1143e2080de27cdeb587b42d9187e6254ab46634/src/ios/CDVNodeJS.mm#L57
This is the part that send messages to Node: https://github.com/janeasystems/nodejs-mobile-cordova/blob/1143e2080de27cdeb587b42d9187e6254ab46634/src/ios/CDVNodeJS.mm#L123-L125
To make the JS part of the bridge available at runtime, it can be included as if it was a npm package in the `node_modules` of a node project folder or its runtime path can be included in the `NODE_PATH` environment variable (which is what the cordova plugin does here https://github.com/janeasystems/nodejs-mobile-cordova/blob/1143e2080de27cdeb587b42d9187e6254ab46634/src/ios/CDVNodeJS.mm#L73).

Regarding the npm question:
There's a sample in the sample repos that is built on top of the "Getting Started" sample: https://github.com/janeasystems/nodejs-mobile-samples/tree/master/ios/native-xcode-node-folder
This sample starts the project from a `nodejs-project` folder where you can install npm modules to be included in the application before building it. If what you intend is to use npm at runtime, it might not be possible to do it according to Apple's guidelines. More discussion about this can be found here: https://github.com/janeasystems/nodejs-mobile/issues/7

I hope this was helpful.

**Comment by SlayterDev** [comment]
This certainly helps. One more question: How can I quit a Node process after I start it?

**Comment by jaimecbernardo** [comment]
The Node runtime doesn't run in a separate process, it runs in the application process. iOS runtime won't allow you to create new processes, as far as I know, so the current use case for the library is using a single instance of the node runtime in the application's process.

The main issue is that the node runtime can make the assumption that it is running in a dedicated process and that may bring some problems in terms of clean up between runs. It's possible that you can let the node runtime terminate, by making sure you close all the ports, timeouts and anything that is waiting on a event from the node side and then try to restart it. It's just untested at the moment.
