### ISSUE TITLE
WebRTC not working

### ISSUE THREAD

**Issue by d3b00** [janeasystems/nodejs-mobile#63]
All the modules that I have tried thus far give me the same results as I get when I run Node.js on Windows except for WebRTC. I cannot get WebRTC to work on nodejs-mobile Android while it works perfectly on Windows. Any ideas?

**Comment by jaimecbernardo** [comment]
Hi @d3b00 ,
Would you be able to provide more information? Are you using a plugin? What errors are you getting?
Thank you, in advance.

**Comment by d3b00** [comment]
I am getting the error because I'm trying to use a library which only supports x64 bit systems and my android device is ia32. So, its not nodejs-mobile's fault I guess.
