### ISSUE TITLE
configure NODE_ENV variable when starting node server

### ISSUE THREAD

**Issue by dudwchina** [janeasystems/nodejs-mobile#72]
* **Version**:v8.6.0
* **Platform**:Darwin localhost 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

I've been looking for some ways to set NODE_ENV=development before starting node server, something like NODE_ENV=development node app.js, with nodejs-mobile, but I have failed in doing such. 
I couldn't find a clear way of doing it ,If there is already a way to do it?

My target is iOS.start node server code as below.

```Objective-C
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
        NSArray* nodeArguments = [NSArray arrayWithObjects:
                                  @"NODE_ENV=development node",
                                 pathOfAppjs,
                                  nil
                                  ];
        [NodeRunner startEngineWithArguments:nodeArguments];
    });
````
Thanks

**Comment by jaimecbernardo** [comment]
Hi @dudwchina ,

`NODE_ENV=development` would be the way to define an environment variable before starting node if you were in a shell.
For setting environment variables in an embedded scenario, you'll have to use the platform tools for this. Calling `setenv` would be a way to achieve this: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/getenv.3.html

That's the technique we're using in the plugins to set `NODE_PATH`, for example: https://github.com/janeasystems/nodejs-mobile-cordova/blob/0eab389a5d5ef2c9cacc246449a02e3cb8a6ed1a/src/ios/CDVNodeJS.mm#L113

**Comment by dudwchina** [comment]
@jaimecbernardo  thanks for the answer, `setenv ` function works for me.😄
