### ISSUE TITLE
License for nodejs-mobile-cordova

### ISSUE THREAD

**Issue by lastmjs** [janeasystems/nodejs-mobile#73]
It would be nice to have an explicit license in this repo: https://github.com/janeasystems/nodejs-mobile-cordova

**Comment by orangemocha** [comment]
Thanks for bringing this issue to our attention.
Fixed in https://github.com/janeasystems/nodejs-mobile-cordova/commit/d71a51aae7ae5a01c4970147d67537320106145f.
