### ISSUE TITLE
TypeError: nodejs.channel.on is not a function

### ISSUE THREAD

**Issue by zhish3n** [janeasystems/nodejs-mobile#76]
The sample code works perfectly, but now I'm getting this 'TypeError: nodejs.channel.on is not a function' error when I'm trying to swap out '.send' with '.on'. Any suggestions?

**Comment by jaimecbernardo** [comment]
Hi @ZhiSh3n , Are you using the react-native plugin?
Try `setListener`, as mentioned in the README.md: https://github.com/janeasystems/nodejs-mobile-react-native/tree/05e1748831bca8b8f053dcf80a348f3dc782596c#react-native-application
