### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by xxfenxx** [janeasystems/nodejs-mobile#77]
* **v0.1.4**:
* **x86/64-bit**:
* **iOS**:

```
dyld: Library not loaded: @rpath/NodeMobile.framework/NodeMobile
  Referenced from: /var/containers/Bundle/Application/0EADD8A5-1145-42E0-9221-7952770FBE72/native-xcode-node-folder.app/native-xcode-node-folder
  Reason: image not found
```

download codes from link 

When I run the the project it crash and show me the message above. And I can not get resole method for this.

----

when I try install Node by Cocoapods , it show me an error : 

```
Installing Node (4.2.4)
[!] Error installing Node
[!] Unable to locate the executable `hg`
```

**Comment by xxfenxx** [comment]
I solve my problem by : https://blog.csdn.net/wang631106979/article/details/55258478 and https://stackoverflow.com/questions/17179975/cocoapods-unable-to-locate-the-executable-hg-error-while-pod-install-core-p

**Comment by jaimecbernardo** [comment]
Hi @LiangyongFShen , was about to answer this.

I was going to suggest this might've been from the `NodeMobile.framework` not being added as an embedded binary, as mentioned here: https://github.com/janeasystems/nodejs-mobile-samples/tree/master/ios/native-xcode#embed-the-libnodeframework-in-the-binary

Didn't know you could also solve this by a copy phase. If that causes further issues, try the Embedded Binaries route. Thank you for your comments.
