### ISSUE TITLE
Problem with grpc_node.node

### ISSUE THREAD

**Issue by zhish3n** [janeasystems/nodejs-mobile#79]
Hi, I'm trying to use Google's text-to-speech API with this plugin. However, when I try to create a speech client I get this error:

`Error: dlopen failed: "/data/data/io.cordova.hellocordova/files/www/nodejs-project/node_modules/@google-cloud/text-to-speech/node_modules/grpc/src/node/extension_binary/node_abi-platform-arch-unknown/grpc_node.node" has bad ELF magic`

Any kind of help is appreciated. I apologize if this issue is too off-topic.

**Comment by pjc0247** [comment]
I have a same problem

I suppose the problem is when I type `npm install`, `node-pre-gyp` downloads the prebuilt binaries based on current system (PC).
but we need to run these stuffs on Android.

**Comment by jaimecbernardo** [comment]
Hi @ZhiSh3n and @pjc0247 ,
Those modules contain native code, which needs to be compiled for the target architecture. Please try to use the experimental feature to turn on native modules building, as described in the native modules issue: https://github.com/janeasystems/nodejs-mobile/issues/4#issuecomment-371555631

**Comment by zhish3n** [comment]
@jaimecbernardo Thanks for the quick reply! I will try this as soon as I can and get back to this thread.

**Comment by zhish3n** [comment]
I'm trying native modules binding on Windows but I get the message that 'NODEJS_MOBILE_BUILD_NATIVE_MODULES' is not recognized as a command. Is there a way to get it working on Windows or should I use Linux system instead?

**Comment by jaimecbernardo** [comment]
Hi @ZhiSh3n , as mentioned in the instructions, this experimental feature is implemented for macOS and Linux only. In the issue I linked early there is a report of a successful build in Windows using WSL, but I'd recommend using macOS or Linux.

**Comment by pjc0247** [comment]
@jaimecbernardo 

I got a this error when I tried with WSL.

```
error: unknown argument: '-zdefs'
```
```
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
clang60++: error: unknown argument: '-zdefs'
make: *** [Release/obj.target/grpc_node/ext/byte_buffer.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/f/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
```

**Comment by pjc0247** [comment]
@jaimecbernardo Sry it was not a problem related with `nodejs-mobile`. I'll fix it

**Comment by jaimecbernardo** [comment]
Hi @pjc0247 , Try to use grpc@1.12.3 , I've been able to build that version successfully, and it doesn't contain `-zdefs` anymore: https://github.com/grpc/grpc-node/commit/029042235606c6e6064e4428f73ad801142872f7

**Comment by pjc0247** [comment]
@jaimecbernardo Thank you! I've made a build and works fine on Android.
