### ISSUE TITLE
Getting started with Android

### ISSUE THREAD

**Issue by mnleano** [janeasystems/nodejs-mobile#80]
* **Version**: v9.6.1
* **Platform**: Darwin Mykels-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64
* **Subsystem**:

**Hey there!**
I followed the instructed written in here [Getting started Android app](https://code.janeasystems.com/nodejs-mobile/getting-started-android)

Once I finish following the instruction and running the app.
The app will only open for about a second then close.

There's no indication of error in the Logcat. 

Thanks!

**Comment by mnleano** [comment]
`06-20 14:09:54.863 20154-20171/com.dapperwallet.nodejsmobile I/TMSDISP: AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter
    AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter2
    AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - mSource2
    AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Exit`

I've got something in the Logcat. 
Hope it will helps!

**Comment by jaimecbernardo** [comment]
Hi @mnl-assasin , Another sample shows how to redirect the processe's `stdout` and `stderr` streams (used by node for reporting errors) to logcat. This might help in understanding what's wrong. https://github.com/janeasystems/nodejs-mobile-samples/tree/master/android/native-gradle-node-folder#redirect-the-stdout-and-stderr-to-logcat

**Comment by mnleano** [comment]
Hi @jaimecbernardo thanks for the help. 
I determine the error. However, I can't seem to find a solution. 
I know for sure I followed the every given instruction. 

Here's my logcat error

`Error: listen EACCES 0.0.0.0:4000
        at Object._errnoException (util.js:1019:11)
        at _exceptionWithHostPort (util.js:1041:20)
        at Server.setupListenHandle [as _listen2] (net.js:1327:19)
        at listenInCluster (net.js:1385:12)
        at Server.listen (net.js:1469:7)
        at [eval]:1:180
        at ContextifyScript.Script.runInThisContext (vm.js:50:33)
        at Object.runInThisContext (vm.js:139:38)
        at Object.<anonymous> ([eval]-wrapper:6:22)
        at Module._compile (module.js:624:30)`

**Comment by jaimecbernardo** [comment]
Hi @mnl-assasin 
It seems like the error is in listening to the port. Have you given the following permissions? https://github.com/janeasystems/nodejs-mobile-samples/tree/master/android/native-gradle#add-internet-permissions-to-manifest
Trying other port might help. While searching for "EACCES android server" I got the following link that talks about more permissions that may affect this: https://stackoverflow.com/a/29720600/4594761
Let us know if this was helpful.

**Comment by mnleano** [comment]
Woah silly of me! 
I forgot to check and add that permission!
It works now. Thank you so much!
