### ISSUE TITLE
dlopen("........../lib/x86_64/libnative-lib.so", RTLD_LAZY) failed: 

### ISSUE THREAD

**Issue by CoNETProject** [janeasystems/nodejs-mobile#81]
Hi 

I got dlopen error.

* Node.js for Mobile Apps core library v0.1.5
*Android Studio 3.1.3
*Build #AI-173.4819257, built on June 4, 2018
*JRE: 1.8.0_152-release-1024-b01 x86_64
*JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
*Mac OS X 10.13.5

```
dlopen("........../lib/x86_64/libnative-lib.so", RTLD_LAZY) failed:
dlopen failed: could not load library "libnode.so" needed by 
"......../lib/x86_64/libnative-lib.so"; 
caused by cannot locate symbol "_Unwind_Backtrace" referenced by "libnode.so"

java.lang.UnsatisfiedLinkError: dlopen failed: 
could not load library "libnode.so" needed by "......./lib/x86_64/libnative-lib.so"; 
caused by cannot locate symbol "_Unwind_Backtrace" referenced by "libnode.so"...
```

this will error --->   **System.loadLibrary("native-lib");**

My project running good at Android P. Other Android version looks **FATAL EXCEPTION**

**Comment by jaimecbernardo** [comment]
Hi @QTGate , 

Just tried to run a sample application on an Android API 23 x86_64 simulator with the "Node.js for Mobile Apps core library v0.1.5" and it ran.

Could you please provide more information / a repo with a project to reproduce the issue?

**Comment by CoNETProject** [comment]
Hi Jaime Bernardo,

Thank you for your reply.

I tried to run 'nodejs-mobile-samples-master/native-gradle-node-folder' with "Node.js for Mobile Apps core library v0.1.5" it was failed with same issue.
I tried running same and it was fine before I update my Android Studio to new:
Looks this issue happened when Android Studio  uploaded to:
```
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
NDK: r17b(June 2018)
Mac OS X 10.13.5

```
I think maybe the latest NDK have not support Node.js for Mobile Apps core library
I will try again when I downgrade my NDK to 16b.
Peter


```
06-24 13:18:27.855 7845-7845/? I/art: Not late-enabling -Xcheck:jni (already on)
06-24 13:18:27.875 7845-7853/? E/art: Failed sending reply to debugger: Broken pipe
06-24 13:18:27.875 7845-7853/? I/art: Debugger is no longer active
06-24 13:18:27.962 7845-7845/? I/InstantRun: starting instant run server: is main process
06-24 13:18:27.996 7845-7845/? E/art: dlopen("/data/app/com.yourorg.sample-1/lib/x86_64/libnative-lib.so", RTLD_LAZY) failed: dlopen failed: could not load library "libnode.so" needed by "/data/app/com.yourorg.sample-1/lib/x86_64/libnative-lib.so"; caused by cannot locate symbol "_Unwind_Backtrace" referenced by "libnode.so"...
06-24 13:18:27.997 7845-7845/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
06-24 13:18:27.997 7845-7845/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yourorg.sample, PID: 7845
    java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libnode.so" needed by "/data/app/com.yourorg.sample-1/lib/x86_64/libnative-lib.so"; caused by cannot locate symbol "_Unwind_Backtrace" referenced by "libnode.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:989)
        at com.yourorg.sample.MainActivity.<clinit>(MainActivity.java:21)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1572)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by jaimecbernardo** [comment]
Hi @QTGate , Gave it a try again after updating Android Studio to and the NDK:
```
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

NDK: 17.1.4828580 ( version shown in the Android SDK manager. It's r17b, as far as I know. )
```

Are you getting this error in an emulator or in a specific x86_64 device? I think the "_Unwind_Backtrace" symbol should come from Android's C++ STL libraries in the device or emulator you're running on.

**Comment by lurkerCha** [comment]
I had similar error. I solved it by updating my emulator android version to 8.0

**Comment by jaimecbernardo** [comment]
I've been able to reproduce this error in Android 7 devices, for arm64 builds, but only when the Application is built with the NDK r17b.

The reason is that the nodejs-mobile binaries are built with android NDK r16b. Some symbols that are included by the NDK r16b linking to `libc++_shared.so` seem to not be included in the 64 bits `libc++_shared.so` binaries that NDK r17b includes in the Application's APK. This seems to affect Android 7.0 64 bit runtimes.

Using NDK r16b for the Application solves this issue. Building nodeLib with r17b also solves this issue for Applications that are built with with r17b or r16b.
We will start using NDK r17b for the next library Android builds.

**Comment by jaimecbernardo** [comment]
This issue should have been solved by the latest release of the [core library v0.1.7](https://github.com/janeasystems/nodejs-mobile/releases/tag/nodejs-mobile-v0.1.7).
