### ISSUE TITLE
Calling native so files from NodeJS on Android

### ISSUE THREAD

**Issue by Lidanha** [janeasystems/nodejs-mobile#88]
Is calling native so files on Android is supported like using ffi for Node on Windows?

**Comment by jaimecbernardo** [comment]
Hi @Lidanha ,
I'm not sure about `ffi` on Android, but there's an experimental native module support in the plugins, so it could be possible. Here's a link to the native modules issue: https://github.com/janeasystems/nodejs-mobile/issues/4#issuecomment-371555631

**Comment by Lidanha** [comment]
Thank you, I was able to get this working with native module support on Android pretty easily using the NODEJS_MOBILE_BUILD_NATIVE_MODULES=1 variable. This issue can be closed.

**Comment by jaimecbernardo** [comment]
Good to know. Closing this issue, then. Thank you.
