### ISSUE TITLE
Browser Integration?

### ISSUE THREAD

**Issue by SourceBoy** [janeasystems/nodejs-mobile#89]
Hi Janea Systems,

Do you have plans to integrate Node.js with a browser (e.g. Chromium) directly? Similar to what Electron and NW have done for desktop, but for mobile.

**Comment by jaimecbernardo** [comment]
Hi @SourceBoy ,

At the current time, this is not a planned feature for the core library.

There are plugins for using this library in popular mobile UI frameworks, such as Cordova: https://github.com/janeasystems/nodejs-mobile-cordova and React Native: https://github.com/janeasystems/nodejs-mobile-react-native

Integration with other frameworks or a new project that does what you've asked should be possible by using the core library.

**Comment by SourceBoy** [comment]
Thanks for the response. I'm aware of the current plugins; great job you guys have done here.
