### ISSUE TITLE
Use native modules that came with prebuilt binaries

### ISSUE THREAD

**Issue by Lidanha** [janeasystems/nodejs-mobile#90]
Hey,

I see that node-pre-gyp is executed when I try to 'cordova build android' my project. It leads to unexpected results. To my understanding it's because the specific package I'm installing has some prebuilt binaries (for Linux - not for Android). Is there any way I can avoid them and pass the build-from-source parameter to the native build command and this way these binaries will be built for Android (hopefully)?

I hope my question is clear
Lidan

**Comment by jaimecbernardo** [comment]
Hi, @Lidanha ,
On the most recent version of nodejs-mobile-cordova, it is [trying to automatically detect native modules](https://github.com/janeasystems/nodejs-mobile-cordova/tree/cc28cb335f11d8b6d87e61f4818ef8e837094cdb#native-modules) and rebuilding it for the Android OS. This command also passes the `--build-from-source` to `npm rebuild` in case `node-pre-gyp` is used by any of the modules:
https://github.com/janeasystems/nodejs-mobile-cordova/blob/cc28cb335f11d8b6d87e61f4818ef8e837094cdb/src/android/build.gradle#L213

What module is having issues? For module build issues, would you mind opening an issue describing the module's error in this repo: https://github.com/janeasystems/nodejs-mobile-module-compat

**Comment by Lidanha** [comment]
Thanks @jaimecbernardo 
I just installed the latest version. Will check and update with more specific details

**Comment by Lidanha** [comment]
OK this issue can be closed. I think I had some environment issues that somehow got fixed (by running cordova clean)
Thank you @jaimecbernardo

**Comment by jaimecbernardo** [comment]
Thank you for letting us know and glad it worked. Closing this issue.
