### ISSUE TITLE
A problem was found with the configuration of task ':app:generateJsonModelDebug'

### ISSUE THREAD

**Issue by newmips** [janeasystems/nodejs-mobile#94]
Hi,
Getting the error in title when trying to create cordova android app. Executed following instructions:
> cordova plugin add nodejs-mobile-cordova ----> OK
> cordova build android -----> KO

Message says:
A problem was found with the configuration of task ':app:generateJsonModelDebug'.
> File '/home/denis/AndroidStudioProjects/TestApp/platforms/android/app/src/com/janeasystems/cdvnodejsmobile/jni/CMakeLists.txt' specified for property 'externalNativeJsonGenerator.makefile' does not exist.

Using tools:
node 8.10.0
cordova 8.0.0
gradle 3.4.1

I have currently no folder "com/janeasystems/cdvnodejsmobile/" in subdirectory "platforms/android/app/src/". 
Can you help to clarify what has to be done to build those files or solve this issue? Thanks for your help.
Note. Maybe this issue is related to https://github.com/janeasystems/nodejs-mobile/issues/90

**Comment by jaimecbernardo** [comment]
Hi @newmips ,

As stated in the [Requirements](https://github.com/janeasystems/nodejs-mobile-cordova/tree/cc28cb335f11d8b6d87e61f4818ef8e837094cdb#requirements), Cordova 8.x is not supported.
That's probably where the error is coming from.

**Comment by newmips** [comment]
Ah! Thanks. I was misleading by this page https://code.janeasystems.com/nodejs-mobile/getting-started-cordova which indicates Cordova 7.0.0 or higher.
Will downgrade version and test again.

**Comment by jaimecbernardo** [comment]
@newmips , Thank you for pointing that out. Corrected the requirements in that page.

**Comment by newmips** [comment]
Tested again. It actually works with cordova 7.0.0. Thx @jaimecbernardo !

**Comment by home-grown-engineer** [comment]
Hi!
Got same error on cordova 7.0.0

```
BUILD FAILED in 4s
28 actionable tasks: 8 executed, 20 up-to-date
Error: /Users/username/Documents/Work/project/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:generateJsonModelDebug'.
> File '/Users/username/Documents/Work/project/platforms/android/app/src/com/janeasystems/cdvnodejsmobile/jni/CMakeLists.txt' specified for property 'externalNativeJsonGenerator.makefile' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
➜ git:(develop) ✗ ./node_modules/.bin/cordova --version  
7.0.0
➜ git:(develop) ✗ cordova --version
7.0.0
➜  git:(develop) ✗ 
```

**Comment by jaimecbernardo** [comment]
Hi @britishd ,
The path that's being looked for by cordova `platforms/android/app/` was introduced by "cordova-android 7.X". Cordova 7.X would come with "cordova-android 6.X", which shouldn't have this issue, to the best of my knowledge.
Was the project created with Cordova 8.X ?

One way to verify the "android" platform version is to run `cordova platforms` inside the project. The android platform version should be 6.X

**Comment by andreddosantos** [comment]
Hello guys, 

I'm experiencing the same error.
`ionic info`

> Ionic:
> 
>    ionic (Ionic CLI)             : 4.2.1 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework               : @ionic/angular 4.0.0-beta.7
>    @angular-devkit/build-angular : 0.7.5
>    @angular-devkit/schematics    : 0.7.5
>    @angular/cli                  : 6.1.5
>    @ionic/angular-toolkit        : not installed
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 7.1.0
>    Cordova Platforms     : android 6.3.0, ios 4.5.5
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 5 other plugins)
> 
> System:
> 
>    ios-deploy : 2.0.0
>    NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
>    npm        : 6.4.1
>    OS         : macOS High Sierra
>    Xcode      : Xcode 9.4.1 Build version 9F2000

`cordova platforms`
> Installed platforms:
>   android 6.3.0
>   ios 4.5.5
> Available platforms:
>   blackberry10 ~3.8.0 (deprecated)
>   browser ~5.0.0
>   osx ~4.0.1
>   ubuntu ~4.3.4 (deprecated)
>   webos ~3.7.0
>   windows ~5.0.0
>   www ^3.12.0

[error_stack.txt](https://github.com/janeasystems/nodejs-mobile/files/2468984/error_stack.txt)

Well for ios all smooth, regarding android a lot of issues.

Regards

**Comment by jaimecbernardo** [comment]
Hi @andreddosantos ,
Something in the build system is introducing a flag that is not recognized by CMake. It's in the logs you've shared:
```
  clang: error: unknown argument: '-nostdlib++'
```
Is this happening on the sample you've shared in https://github.com/janeasystems/nodejs-mobile-samples/pull/10, as well?

**Comment by andreddosantos** [comment]
Hello @jaimecbernardo

> Is this happening on the sample you've shared in janeasystems/nodejs-mobile-samples#10, as well?

 it should be, since the configurations for that PR are the same for the app i'm working on, but the thing is, i believe that this is not ionic related, since it is cordova that generates the FS for the platform applications, all ionic files ends up in the www folder as js parsed by webpack ... 

I'm going to do my debug regarding the information you just gave me, and I'll try to let you know the origin of that flag. `'-nostdlib++'`

BTW if you want to replicate, after having the environment set up with the versions i've already posted here, you just need to run the following commands

iOS working:
`ionic cordova platform add ios --save`
`ionic cordova build ios` 

Android:
`ionic cordova platform add android --save` 
`ionic cordova build android`      //not working

regards
André

**Comment by andreddosantos** [comment]
Nope that flag does not exist in the project directory...

Going through all the Android instalation steps:

- Install SDK; (Android 9 pie)
- Install NDK; (android-ndk-r16b-darwin-x86_64)
- Assign the NDK path to global variable (export ANDROID_NDK_HOME=/Users/username/Library/Android/sdk/ndk-bundle)
-Run build with cordova; (7 >= version < 8)

This has nothing to with Ionic i believe but some android or cordova setting. Am i missing any kind of step?

Regards
André

**Comment by andreddosantos** [comment]
It was local wrong local Android environment settings! Thanks

**Comment by jaimecbernardo** [comment]
Hi @andreddosantos ,
Good to know it's been solved.
Which setting was causing this behavior?

**Comment by chiemekailo** [comment]
> It was local wrong local Android environment settings! Thanks

Hi @andreddosantos, which environment settings was causing this?
