### ISSUE TITLE
stdin immediately ends

### ISSUE THREAD

**Issue by zoecarver** [janeasystems/nodejs-mobile#99]
* **Version**: v8.6.0
* **Platform**: iOS 11.4

When I try add a listener to the `process.stdin` stream, it immediately ends. 

### Javascript
```javascript
console.log('started reader')

process.stdin.setEncoding('utf8');

process.stdin.on('readable', () => {
	const chunk = process.stdin.read();
	if (chunk !== null) {
		process.stdout.write(`data: ${chunk} \n`);
	}
});

process.stdin.on('end', () => {
	process.stdout.write('end \n');
});

```

### Output
```
started reader
end 
```

### Edit [feature-request]
Also it would be really great if we could set our own output/input streams so that we could pipe stuff from the app to the nodejs instance and vice versa.

**Comment by jaimecbernardo** [comment]
Hi @pudility ,

Command line input (stdin) is not available on an iOS application, which makes sense.
It's currently possible to set output/input streams and use those as a communication method. You can set those up before starting the nodejs runtime and pass the file handler as an argument to the node runtime.

We've used this technique in an old demo of the project to send when the iOS app went to the background/foreground.

https://github.com/janeasystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/ios/PouchAlbum/AppDelegate.m#L40-L47

Creating the pipe and passing the file descriptor as an argument to node:
https://github.com/janeasystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/ios/PouchAlbum/NodeRunner.mm#L19-L24
https://github.com/janeasystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/ios/PouchAlbum/NodeRunner.mm#L83-L96

Reading the file handler and using it in the node side:
https://github.com/janeasystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/nodeproj/main.js#L222-L225
https://github.com/janeasystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/nodeproj/main.js#L188-L218

**Comment by zoecarver** [comment]
That is super helpful, completely solved my problem. Thanks!
